// ── THE CHART ROOM'S WEEKLY BOARDS, BUILT (Steam prep, 2026-09-29) ──
//
// How each of the four weekly puzzles is made, with nothing of the web in it.
// All four are generated by code (no Claude): Treasure Match is a seed, the
// Minefield, the Hold and the Rigging come out of their pure engines. The web's
// generators (charting/generate, minefieldGenerate, hold/generate,
// rigging/generate) call these and cache the result per week for everyone; the
// offline store calls them and keeps the result in the save. Every roll goes
// through lib/rng, so a seeded offline game builds the same boards on replay.

import { rngNext } from '@/lib/rng'
import { MATCH_COLS, MATCH_ROWS, MATCH_TYPES, MATCH_TARGET, MATCH_MOVES } from '@/app/(app)/charting/constants'
import { MINEFIELD_COLS, MINEFIELD_ROWS, MINEFIELD_MINES } from '@/app/(app)/charting/minefieldConstants'
import { generateBoard as generateMinefield } from '@/app/(app)/charting/minefield'
import { HOLD_DIFFICULTIES, HOLD_META, type HoldDifficulty } from '@/app/(app)/tavern/chart-room/hold/constants'
import { generatePuzzle, type SudokuPuzzle } from '@/app/(app)/tavern/chart-room/hold/sudoku'
import { RIGGING_COLS, RIGGING_ROWS, RIGGING_COLORS } from '@/app/(app)/tavern/chart-room/rigging/constants'
import { generateBoard as generateRigging, type RiggingPair } from '@/app/(app)/tavern/chart-room/rigging/rigging'

export type { SudokuPuzzle } from '@/app/(app)/tavern/chart-room/hold/sudoku'

export interface MatchConfig {
  seed: number
  cols: number
  rows: number
  types: number
  target: number
  moves: number
}

export interface MinefieldLayout {
  cols: number
  rows: number
  mineCount: number
  mines: number[]    // SERVER-ONLY: never reaches a client
  opening: number[]
}

export type SudokuSet = Record<HoldDifficulty, SudokuPuzzle>

export interface RiggingLayout {
  cols: number
  rows: number
  pairs: RiggingPair[]
}

/** Treasure Match: a seed; the board and its drop order follow from it. */
export function buildMatchConfig(): MatchConfig {
  return {
    seed: Math.floor(rngNext() * 0x7fffffff),
    cols: MATCH_COLS, rows: MATCH_ROWS, types: MATCH_TYPES, target: MATCH_TARGET, moves: MATCH_MOVES,
  }
}

/** The Minefield: mines and a guaranteed-safe opening. Throws on a bad board. */
export function buildMinefieldLayout(): MinefieldLayout {
  const { mines, opening } = generateMinefield(MINEFIELD_COLS, MINEFIELD_ROWS, MINEFIELD_MINES)
  const layout = { cols: MINEFIELD_COLS, rows: MINEFIELD_ROWS, mineCount: MINEFIELD_MINES, mines, opening }
  if (layout.mines.length !== MINEFIELD_MINES || layout.opening.length === 0) throw new Error('Bad board')
  return layout
}

/** The Hold: four sudoku, one per difficulty, each with a unique solution. Throws on a bad one. */
export function buildSudokuSet(): SudokuSet {
  const set = Object.fromEntries(HOLD_DIFFICULTIES.map(d => [d, generatePuzzle(HOLD_META[d].givens)])) as SudokuSet
  for (const d of HOLD_DIFFICULTIES) {
    const p = set[d]
    if (!p || p.givens.length !== 81 || p.solution.length !== 81) throw new Error(`Bad puzzle for ${d}`)
  }
  return set
}

/** A cached set is stale if it predates a difficulty (e.g. the week the 4th
 *  hold was added), so it must be regenerated to include all four. */
export function hasAllDifficulties(set: unknown): set is SudokuSet {
  return !!set && HOLD_DIFFICULTIES.every(d => {
    const p = (set as Record<string, unknown>)[d] as { givens?: string } | undefined
    return typeof p?.givens === 'string'
  })
}

/** The Rigging: endpoint pairs of a board solvable by construction. Throws on a bad board. */
export function buildRiggingLayout(): RiggingLayout {
  const board = generateRigging(RIGGING_COLS, RIGGING_ROWS, RIGGING_COLORS)
  const layout = { cols: board.cols, rows: board.rows, pairs: board.pairs }
  if (layout.pairs.length !== RIGGING_COLORS) throw new Error('Bad board')
  return layout
}
