// The Exchange: what you can take a contract on, for how long, and what it pays.
//
// A contract is NOT a share. You never own the fish, there is no inventory, and
// nothing here touches fish_inventory or the selling lanes. You stake doubloons
// on a direction over a term; at expiry the contract settles itself against the
// exchange price and either pays out or expires worthless.
//
// Prices come from fish_exchange, NOT fish_market. See
// supabase/migrate_fish_exchange.sql for why that separation is load-bearing:
// the sell market deliberately pulls every price back to 1.00, which would make
// speculating on it a risk-free annuity rather than a bet.

/** Contract terms, in market cycles. The market ticks hourly, so these are 6
 *  hours, a day, and three days. Each is about 3x the last, so the odds and the
 *  payouts differ enough that choosing between them is a real decision.
 *
 *  Every contract SETTLES ITSELF at expiry whether the player is online or not.
 *  A contract that expired worthless must always mean the market went against
 *  you, never that you were asleep. */
export const TERMS = [6, 24, 72] as const
export type Term = typeof TERMS[number]

export const TERM_LABEL: Record<Term, string> = {
  6: 'Short', 24: 'Day', 72: 'Long',
}
export const TERM_BLURB: Record<Term, string> = {
  6: 'Settles in 6 hours',
  24: 'Settles tomorrow',
  72: 'Settles in three days',
}

export type Direction = 'rise' | 'fall'

/** The house edge, taken out of the payout rather than charged as a fee. Every
 *  instrument and every term is fair to exactly this degree, which is the point
 *  of deriving the leverage rather than picking round numbers: otherwise some
 *  contracts are quietly better bets than others and the board has a "correct"
 *  answer. */
export const HOUSE_EDGE = 0.08

// ── Payout leverage ─────────────────────────────────────────────────────────
// payout = stake x L x max(0, move% in your direction)
//
// L is set so E[payout] = stake x (1 - HOUSE_EDGE). Break-even move is 1/L.
//
// GENERATED by scripts/derive-exchange-payouts.mjs, which simulates the shipped
// engine. Do not hand-edit: rerun it if the engine's volatility, theta or mood
// weights ever change, or these silently stop being fair.

/** Single fish, keyed by bite_rarity. A legendary swings hardest, so it needs
 *  the least leverage to reach the same expected payout. */
export const SINGLE_LEVERAGE: Record<number, Record<Term, number>> = {
  1: { 6: 0.495, 24: 0.272, 72: 0.206 },
  2: { 6: 0.399, 24: 0.219, 72: 0.166 },
  3: { 6: 0.321, 24: 0.173, 72: 0.130 },
  4: { 6: 0.257, 24: 0.138, 72: 0.103 },
  5: { 6: 0.203, 24: 0.108, 72: 0.080 },
}

/** Funds, keyed by how many fish are in them. A fund is an average, so the
 *  idiosyncratic noise cancels and only the shared market mood survives: a fund
 *  moves a fraction as far as any of its members and therefore needs several
 *  times the leverage. Interpolated between these anchors. */
const FUND_LEVERAGE_ANCHORS: [members: number, lev: Record<Term, number>][] = [
  [8,   { 6: 0.771, 24: 0.426, 72: 0.327 }],
  [20,  { 6: 0.988, 24: 0.542, 72: 0.418 }],
  [35,  { 6: 1.084, 24: 0.591, 72: 0.462 }],
  [146, { 6: 1.237, 24: 0.666, 72: 0.520 }],
]

export function fundLeverage(members: number, term: Term): number {
  const a = FUND_LEVERAGE_ANCHORS
  if (members <= a[0][0]) return a[0][1][term]
  if (members >= a[a.length - 1][0]) return a[a.length - 1][1][term]
  for (let i = 1; i < a.length; i++) {
    if (members <= a[i][0]) {
      const [m0, l0] = a[i - 1], [m1, l1] = a[i]
      const t = (members - m0) / (m1 - m0)
      return l0[term] + (l1[term] - l0[term]) * t
    }
  }
  return a[a.length - 1][1][term]
}

// ── Funds ───────────────────────────────────────────────────────────────────
// Derived from the species table at read time, so a new fish joins its fund
// without anything here being edited. Habitats and rarities only: both are
// properties every species already has, and both make an index somebody can
// actually form an opinion about.

export type FundDef = {
  id: string
  name: string
  blurb: string
  accent: string
}

/** PRESENTATION ONLY. Which species are in a fund is defined once, in SQL, by
 *  the exchange_fund_members view. It briefly lived here as predicates too, and
 *  that would have let settlement and the board disagree about what is in an
 *  index: the one class of bug in a money system that nobody notices until it
 *  pays somebody the wrong amount. */
export const FUNDS: FundDef[] = [
  { id: 'sea',          name: 'The Sea Index',    blurb: 'Every fish on the board, weighted alike.', accent: '#38bdf8' },
  { id: 'shallows',     name: 'Shallows Fund',    blurb: 'Bright water. Small, steady, plentiful.',  accent: '#60a5fa' },
  { id: 'open_waters',  name: 'Open Waters Fund', blurb: 'The working sea, and most of the trade.',  accent: '#34d399' },
  { id: 'deep',         name: 'Deep Fund',        blurb: 'Colder water, better coin.',               accent: '#a78bfa' },
  { id: 'abyss',        name: 'Abyss Fund',       blurb: 'Far from any light, and priced like it.',  accent: '#f87171' },
  { id: 'ancient_deep', name: 'Ancient Fund',     blurb: 'The twelve that still swim down there.',   accent: '#c084fc' },
  { id: 'common',       name: 'Common Index',     blurb: 'What everybody lands, every day.',         accent: '#9aa3ad' },
  { id: 'rare',         name: 'Rare Index',       blurb: 'The middle of the book.',                  accent: '#60a5fa' },
  { id: 'legendary',    name: 'Legendary Index',  blurb: 'The rarest water in the sea. Moves hard.', accent: '#f0c040' },
]

export const FUND_BY_ID = new Map(FUNDS.map(f => [f.id, f]))

/** Closing early costs TIME VALUE, not a flat tax.
 *
 *  It was a flat 20% haircut, which punished the wrong player. Simulated: being
 *  able to close at any hour is worth 1.3x to 2.6x to somebody watching every
 *  tick, and 1.00x to somebody who checks a few times a day. A flat cut takes a
 *  fifth off the passive player, who gained nothing from the option, to guard
 *  against a watcher it barely slows down.
 *
 *  So the fee scales with how much of the term is LEFT, which is what an option
 *  actually gives up when you sell it early:
 *
 *    close with the whole term to run   keep 85%
 *    close halfway through              keep 92.5%
 *    close near expiry                  keep ~100%
 *
 *  Waiting it out costs nothing, taking a spike the hour after you opened costs
 *  something, and the stake cap is still the real backstop against anybody who
 *  wants to sit on the board refreshing. */
export const EARLY_EXIT_MAX_FEE = 0.15

/** What closing right now hands over. `remaining` is cycles left of `term`. */
export function earlyCloseValue(fullValue: number, remaining: number, term: Term): number {
  const left = Math.max(0, Math.min(1, remaining / term))
  return Math.max(0, Math.round(fullValue * (1 - EARLY_EXIT_MAX_FEE * left)))
}

// ── Quoting ─────────────────────────────────────────────────────────────────

export type Quote = {
  leverage: number
  /** The move, in percent, at which the contract returns exactly the stake. */
  breakEvenPct: number
}

export function quoteFund(members: number, term: Term): Quote {
  const leverage = fundLeverage(members, term)
  return { leverage, breakEvenPct: 1 / leverage }
}

export function quoteSingle(rarity: number, term: Term): Quote {
  const leverage = (SINGLE_LEVERAGE[rarity] ?? SINGLE_LEVERAGE[3])[term]
  return { leverage, breakEvenPct: 1 / leverage }
}

/** What a contract pays, given how far the instrument actually moved.
 *
 *  A move against you, or a move your way that never cleared break-even, pays
 *  LESS than the stake, down to nothing. There is no partial refund: this is
 *  the "expires worthless" end of the contract and it has to be able to reach
 *  zero, or the whole thing is a savings account. */
export function settlePayout(stake: number, entry: number, exit: number, dir: Direction, q: Quote): number {
  const movePct = ((exit - entry) / entry) * 100
  const yourWay = dir === 'rise' ? movePct : -movePct
  if (yourWay <= 0) return 0
  return Math.max(0, Math.round(stake * q.leverage * yourWay))
}

/** Smallest and largest a single contract can be.
 *
 *  The cap is the brake behind all the maths: whatever edge somebody eventually
 *  finds in the price engine, this is how much they can push through it at a
 *  time.
 *
 *  These live HERE and not in exchangeActions because that file is 'use server'
 *  and a 'use server' module silently DROPS every non-async export. Importing
 *  them from there compiled clean and then failed the build with an unreadable
 *  Ecmascript error. */
export const MIN_STAKE = 500
export const MAX_STAKE = 250_000

/** Gate. Both skills at 75, so the Exchange opens to someone who has actually
 *  worked both halves of the game rather than rushed one. */
export const EXCHANGE_FISHING_LEVEL = 75
export const EXCHANGE_NAV_LEVEL = 75
