// The Exchange: what you can take a contract on, for how long, and what it pays.
//
// A contract is NOT a share. You never own the fish, there is no inventory, and
// nothing here touches fish_inventory or the selling lanes. You stake doubloons
// on a direction over a term; at expiry the contract settles itself against the
// exchange price and either pays out or expires worthless.
//
// Prices come from fish_exchange, NOT fish_market. See
// supabase/migrate_fish_exchange.sql for why that separation is load-bearing:
// the sell market deliberately pulls every price back to 1.00, which would make
// speculating on it a risk-free annuity rather than a bet.

/** Contract terms, in market cycles. The market ticks hourly, so these are 6
 *  hours, a day, and three days. Each is about 3x the last, so the odds and the
 *  payouts differ enough that choosing between them is a real decision.
 *
 *  Every contract SETTLES ITSELF at expiry whether the player is online or not.
 *  A contract that expired worthless must always mean the market went against
 *  you, never that you were asleep. */
export const TERMS = [6, 24, 72] as const
export type Term = typeof TERMS[number]

export const TERM_LABEL: Record<Term, string> = {
  6: 'Short', 24: 'Day', 72: 'Long',
}
export const TERM_BLURB: Record<Term, string> = {
  6: 'Settles in 6 hours',
  24: 'Settles tomorrow',
  72: 'Settles in three days',
}

export type Direction = 'rise' | 'fall'

/** The house edge, taken out of the payout rather than charged as a fee. Every
 *  instrument and every term is fair to exactly this degree, which is the point
 *  of deriving the leverage rather than picking round numbers: otherwise some
 *  contracts are quietly better bets than others and the board has a "correct"
 *  answer. */
export const HOUSE_EDGE = 0.08

// ── Payout leverage ─────────────────────────────────────────────────────────
// payout = stake x L x max(0, move% in your direction)
//
// L is set so E[payout] = stake x (1 - HOUSE_EDGE). Break-even move is 1/L.
//
// GENERATED by scripts/derive-exchange-payouts.mjs, which simulates the shipped
// engine. Do not hand-edit: rerun it if the engine's volatility, theta or mood
// weights ever change, or these silently stop being fair.

/** A contract is priced PER DIRECTION.
 *
 *  Prices move in log space, so in percentage terms an up-move is bigger than a
 *  down-move: an instrument can rise 200% and can only ever fall 100%. One
 *  leverage solved on the rise payoff and used for both sides made Fall pay as
 *  little as 43% of a fair return on the Legendary Index, which turns a
 *  direction into a trap rather than a read on the market.
 *
 *  Both sides now return the same 0.92 per 1 staked, which is why Fall asks a
 *  SMALLER move than Rise everywhere: a fall of that size is the rarer event,
 *  so it is worth more per point. */
export type Sided = { rise: number; fall: number }

/** Single fish, keyed by bite_rarity. A legendary swings hardest, so it needs
 *  the least leverage and asks the biggest move to break even. */
export const SINGLE_LEVERAGE: Record<number, Record<Term, Sided>> = {
  // rarity 1: 24h break-even  rise 3.69%  fall 3.46%
  1: { 6: { rise: 0.4919, fall: 0.5139 }, 24: { rise: 0.2709, fall: 0.2888 }, 72: { rise: 0.2084, fall: 0.2171 } },
  // rarity 2: 24h break-even  rise 4.54%  fall 4.20%
  2: { 6: { rise: 0.4002, fall: 0.4197 }, 24: { rise: 0.2201, fall: 0.2379 }, 72: { rise: 0.1648, fall: 0.1817 } },
  // rarity 3: 24h break-even  rise 5.76%  fall 5.09%
  3: { 6: { rise: 0.3192, fall: 0.3428 }, 24: { rise: 0.1736, fall: 0.1964 }, 72: { rise: 0.1298, fall: 0.1512 } },
  // rarity 4: 24h break-even  rise 7.27%  fall 6.18%
  4: { 6: { rise: 0.2558, fall: 0.2785 }, 24: { rise: 0.1375, fall: 0.1618 }, 72: { rise: 0.1025, fall: 0.1257 } },
  // rarity 5: 24h break-even  rise 9.28%  fall 7.46%
  5: { 6: { rise: 0.2041, fall: 0.2279 }, 24: { rise: 0.1078, fall: 0.1341 }, 72: { rise: 0.0799, fall: 0.1051 } },
}

/** Funds, keyed BY ID: each index carries its own roster and rarity mix, so
 *  what it asks of you tracks how far it actually travels. Keying on member
 *  count alone gave Legendary and Common near-identical break-evens despite
 *  legendaries being twice as volatile. */
export const FUND_LEVERAGE: Record<string, Record<Term, Sided>> = {
  // sea: 146 fish, 24h break-even  rise 1.97%  fall 1.24%
  sea: { 6: { rise: 1.0185, fall: 1.4152 }, 24: { rise: 0.5073, fall: 0.8040 }, 72: { rise: 0.3625, fall: 0.6420 } },
  // common: 53 fish, 24h break-even  rise 1.75%  fall 1.46%
  common: { 6: { rise: 1.1040, fall: 1.2474 }, 24: { rise: 0.5711, fall: 0.6859 }, 72: { rise: 0.4174, fall: 0.5300 } },
  // legendary: 47 fish, 24h break-even  rise 2.64%  fall 1.25%
  legendary: { 6: { rise: 0.8173, fall: 1.2478 }, 24: { rise: 0.3791, fall: 0.8000 }, 72: { rise: 0.2643, fall: 0.6633 } },
  // rare: 46 fish, 24h break-even  rise 2.07%  fall 1.42%
  rare: { 6: { rise: 0.9857, fall: 1.2246 }, 24: { rise: 0.4842, fall: 0.7059 }, 72: { rise: 0.3527, fall: 0.5629 } },
  // abyss: 35 fish, 24h break-even  rise 2.37%  fall 1.41%
  abyss: { 6: { rise: 0.8535, fall: 1.1959 }, 24: { rise: 0.4227, fall: 0.7095 }, 72: { rise: 0.2965, fall: 0.5854 } },
  // open_waters: 34 fish, 24h break-even  rise 2.06%  fall 1.46%
  open_waters: { 6: { rise: 0.9667, fall: 1.1928 }, 24: { rise: 0.4864, fall: 0.6840 }, 72: { rise: 0.3526, fall: 0.5309 } },
  // shallows: 33 fish, 24h break-even  rise 2.06%  fall 1.48%
  shallows: { 6: { rise: 0.9530, fall: 1.1842 }, 24: { rise: 0.4856, fall: 0.6749 }, 72: { rise: 0.3433, fall: 0.5348 } },
  // deep: 32 fish, 24h break-even  rise 2.18%  fall 1.45%
  deep: { 6: { rise: 0.9203, fall: 1.1790 }, 24: { rise: 0.4589, fall: 0.6902 }, 72: { rise: 0.3327, fall: 0.5351 } },
  // ancient_deep: 12 fish, 24h break-even  rise 2.76%  fall 1.86%
  ancient_deep: { 6: { rise: 0.7078, fall: 0.9249 }, 24: { rise: 0.3622, fall: 0.5380 }, 72: { rise: 0.2630, fall: 0.4168 } },
}

// ── Funds ───────────────────────────────────────────────────────────────────
// Derived from the species table at read time, so a new fish joins its fund
// without anything here being edited. Habitats and rarities only: both are
// properties every species already has, and both make an index somebody can
// actually form an opinion about.

export type FundDef = {
  id: string
  name: string
  blurb: string
  accent: string
}

/** PRESENTATION ONLY. Which species are in a fund is defined once, in SQL, by
 *  the exchange_fund_members view. It briefly lived here as predicates too, and
 *  that would have let settlement and the board disagree about what is in an
 *  index: the one class of bug in a money system that nobody notices until it
 *  pays somebody the wrong amount. */
export const FUNDS: FundDef[] = [
  { id: 'sea',          name: 'The Sea Index',    blurb: 'Every fish on the board, weighted alike.', accent: '#38bdf8' },
  { id: 'shallows',     name: 'Shallows Fund',    blurb: 'Bright water. Small, steady, plentiful.',  accent: '#60a5fa' },
  { id: 'open_waters',  name: 'Open Waters Fund', blurb: 'The working sea, and most of the trade.',  accent: '#34d399' },
  { id: 'deep',         name: 'Deep Fund',        blurb: 'Colder water, better coin.',               accent: '#a78bfa' },
  { id: 'abyss',        name: 'Abyss Fund',       blurb: 'Far from any light, and priced like it.',  accent: '#f87171' },
  { id: 'ancient_deep', name: 'Ancient Fund',     blurb: 'The twelve that still swim down there.',   accent: '#c084fc' },
  { id: 'common',       name: 'Common Index',     blurb: 'What everybody lands, every day.',         accent: '#9aa3ad' },
  { id: 'rare',         name: 'Rare Index',       blurb: 'The middle of the book.',                  accent: '#60a5fa' },
  { id: 'legendary',    name: 'Legendary Index',  blurb: 'The rarest water in the sea. Moves hard.', accent: '#f0c040' },
]

export const FUND_BY_ID = new Map(FUNDS.map(f => [f.id, f]))

// ── What a live contract is worth ───────────────────────────────────────────
//
// A contract that has not moved your way yet is NOT worthless. It has hours
// left to come good, and that chance is worth money: it is the entire reason
// an option out of the money still trades. The first version paid intrinsic
// value only, so a contract opened one minute ago with three days to run
// valued at nothing, which is nonsense.
//
// The payoff is linear in the move and the move is roughly normal, which is
// the Bachelier case:
//
//   E[max(0, m + X)] = m*Phi(m/s) + s*phi(m/s)
//
// m is how far it has moved your way so far, s is the standard deviation of
// the move still to come. Two properties make this the right answer rather
// than an approximation of it:
//
//   at expiry (s -> 0) it converges exactly to the settlement formula
//   at open (m = 0, full term) it equals stake x (1 - HOUSE_EDGE)
//
// So opening and immediately closing costs you the edge and nothing more, and
// there is never a moment where selling is worth more than the contract is.
// That also quietly kills the timing exploit the old flat fee was guarding
// against: if the exit is always fair, there is nothing to extract by watching.

const INV_SQRT_2PI = 0.3989422804014327

function normPdf(z: number): number {
  return INV_SQRT_2PI * Math.exp(-0.5 * z * z)
}

/** Abramowitz and Stegun 7.1.26. Plenty for pricing a game contract. */
function normCdf(z: number): number {
  const t = 1 / (1 + 0.2316419 * Math.abs(z))
  const d = normPdf(z)
  const p = d * t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))))
  return z >= 0 ? 1 - p : p
}

/** The spread of the move over a FULL term, implied by the leverage we already
 *  solved. L = (1 - edge) / E[max(0,move)] and E[max(0,move)] = 0.3989 * sigma,
 *  so sigma falls straight out and needs no second table to drift from this one. */
function sigmaForTerm(leverage: number): number {
  return (1 - HOUSE_EDGE) / (INV_SQRT_2PI * leverage)
}

/** What the contract is worth RIGHT NOW: intrinsic plus whatever the remaining
 *  time is worth. `remaining` is cycles left of `term`. */
export function liveValue(
  stake: number, leverage: number, movePctYourWay: number, remaining: number, term: Term,
): number {
  if (remaining <= 0) return Math.max(0, Math.round(stake * leverage * Math.max(0, movePctYourWay)))
  const s = sigmaForTerm(leverage) * Math.sqrt(remaining / term)
  if (!(s > 0)) return Math.max(0, Math.round(stake * leverage * Math.max(0, movePctYourWay)))
  const z = movePctYourWay / s
  const expected = movePctYourWay * normCdf(z) + s * normPdf(z)
  return Math.max(0, Math.round(stake * leverage * expected))
}

// ── Quoting ─────────────────────────────────────────────────────────────────

export type Quote = {
  leverage: number
  /** The move, in percent, at which the contract returns exactly the stake. */
  breakEvenPct: number
  /** The move the instrument is EXPECTED to make on its own over the term,
   *  signed the player's way. Zero at par, positive when the drift is helping
   *  them, negative when it is against. Surfaced so the ticket can say so. */
  driftPct: number
  /** The board is expected to move against this contract by MORE than the
   *  contract needs to break even, so it is not a bet. Not listed. */
  blocked: boolean
}

/** The engine's pull back toward par, in log space, per cycle. Must match
 *  update_fish_exchange's THETA exactly. */
export const THETA = 0.015

/** THE PRICE IS NOT THE FORECAST.
 *
 *  The engine mean-reverts: lp = lp - THETA*lp + noise. So an instrument sitting
 *  below par is EXPECTED to climb, and one above par to fall, with no skill or
 *  luck involved. Over `term` cycles the expected log-price decays toward zero
 *  by (1-THETA)^term, so the expected move is known in closed form the moment
 *  the price is.
 *
 *  The leverage tables do not know this: derive-exchange-payouts.mjs starts
 *  every simulated instrument at 1.00, where the drift is exactly zero. Priced
 *  off those tables, a contract opened away from par was not a bet at all.
 *  Simulated against the shipped engine at 10,000 staked on a rarity-3 24h:
 *
 *    start 0.654   Rise paid 26,843   (+168% to the player)
 *    start 0.750   Rise paid 20,069   (+101%)
 *    start 1.000        paid  9,161   (-8%, as intended)
 *    start 1.300   Fall paid 18,000   (+80%)
 *
 *  Today's board runs 0.654 to 1.300, so that was live money. */
export function driftPct(price: number, term: Term, dir: Direction): number {
  if (!(price > 0)) return 0
  const decay = Math.pow(1 - THETA, term)
  const move = (Math.exp(Math.log(price) * (decay - 1)) - 1) * 100
  return dir === 'rise' ? move : -move
}

/** Re-solve the leverage so the contract is worth stake x (1 - edge) again once
 *  the drift is counted.
 *
 *  Payout is stake x L x max(0, move), and with the move now centred on `m`
 *  rather than zero its expectation is the Bachelier form liveValue already
 *  uses: E[max(0, m + X)] = m*Phi(m/s) + s*phi(m/s).
 *
 *  Applied as a RATIO against the table's own par value rather than solved from
 *  scratch, so at par it returns the simulated number unchanged and the analytic
 *  approximation's small error cancels instead of accumulating.
 *
 *  IT ONLY EVER CUTS. The same adjustment run on the side the drift works
 *  AGAINST wants to raise leverage instead, and there the normal approximation
 *  falls apart: it is being asked about the far tail, where the reflecting band
 *  and the 2x mood multiplier bend the real distribution away from anything
 *  closed-form. Simulated, that raise paid 58,171 on a 10,000 stake at the
 *  extreme, which is a worse hole than the one it was closing. This file's own
 *  header says the tables are simulated for exactly that reason.
 *
 *  So the against-drift side keeps its par leverage, unchanged from today. It is
 *  a poor bet, and it always was: buying Fall on something at 0.654 returned 19%
 *  of stake before this change and still does. The difference is that the ticket
 *  now SAYS the instrument is expected to climb 13.8% on its own, so it is a
 *  choice rather than an ambush.
 *
 *  Pricing that side honestly needs a simulated multiplier table, the same way
 *  the par tables were built. Worth doing; not worth guessing at. */
function driftAdjusted(parLeverage: number, drift: number): number {
  if (drift <= 0) return parLeverage
  const s = sigmaForTerm(parLeverage)
  if (!(s > 0)) return parLeverage
  const z = drift / s
  const expected = drift * normCdf(z) + s * normPdf(z)
  if (!(expected > 0)) return parLeverage
  return Math.min(parLeverage, parLeverage * (s * INV_SQRT_2PI) / expected)
}

/** SOME CONTRACTS SHOULD NOT BE WRITTEN AT ALL.
 *
 *  Re-levering the side the drift works against does not have an answer. The
 *  multiplier it wants runs from 17 to 5,061 inside a single band of
 *  drift-over-sigma, because it is a ratio against a denominator heading for
 *  zero: the expected favourable move all but vanishes, and no leverage makes
 *  that fair, only enormous. Simulated at par leverage, buying Fall on a
 *  rarity-1 fish sitting at 0.654 over 72 hours returns 43 doubloons on a
 *  10,000 stake. Disclosure does not fix a number like that. Somebody takes it
 *  by accident.
 *
 *  So it is refused instead, on a rule that explains itself: if the board is
 *  expected to move against you by more than the contract needs to break even,
 *  you would have to reverse the tide AND clear the bar. A book would not list
 *  that, and neither does this one.
 *
 *  TWICE the break-even, not once. At once, today's board would refuse the Fall
 *  leg on 75 of its 146 fish, because the whole board is currently sitting under
 *  par (median 0.848, p90 0.990). Refusing half the board is not protecting
 *  anyone from a trap, it is removing the market.
 *
 *  At twice it refuses 16 fish, which is the tail that actually pays derisory
 *  money: a contract at that distance returns roughly a fifth of its stake,
 *  against about half at the 1x line. The rest stays listed, quoted at par, with
 *  the drift printed on the ticket. */
const BLOCK_AT = 2

function isBlocked(drift: number, breakEvenPct: number): boolean {
  return drift < 0 && Math.abs(drift) > breakEvenPct * BLOCK_AT
}

/** `price` is the instrument's price right now. Omit it and you get the par
 *  quote, which is only correct for something sitting at 1.00. */
export function quoteFund(fundId: string, term: Term, dir: Direction, price?: number): Quote {
  const par = (FUND_LEVERAGE[fundId] ?? FUND_LEVERAGE.sea)[term][dir]
  const drift = price == null ? 0 : driftPct(price, term, dir)
  const leverage = driftAdjusted(par, drift)
  const breakEvenPct = 1 / leverage
  return { leverage, breakEvenPct, driftPct: drift, blocked: isBlocked(drift, breakEvenPct) }
}

export function quoteSingle(rarity: number, term: Term, dir: Direction, price?: number): Quote {
  const par = (SINGLE_LEVERAGE[rarity] ?? SINGLE_LEVERAGE[3])[term][dir]
  const drift = price == null ? 0 : driftPct(price, term, dir)
  const leverage = driftAdjusted(par, drift)
  const breakEvenPct = 1 / leverage
  return { leverage, breakEvenPct, driftPct: drift, blocked: isBlocked(drift, breakEvenPct) }
}

/** What a contract pays, given how far the instrument actually moved.
 *
 *  A move against you, or a move your way that never cleared break-even, pays
 *  LESS than the stake, down to nothing. There is no partial refund: this is
 *  the "expires worthless" end of the contract and it has to be able to reach
 *  zero, or the whole thing is a savings account. */
export function settlePayout(stake: number, entry: number, exit: number, dir: Direction, q: Quote): number {
  const movePct = ((exit - entry) / entry) * 100
  const yourWay = dir === 'rise' ? movePct : -movePct
  if (yourWay <= 0) return 0
  return Math.max(0, Math.round(stake * q.leverage * yourWay))
}

/** Smallest and largest a single contract can be.
 *
 *  The cap is the brake behind all the maths: whatever edge somebody eventually
 *  finds in the price engine, this is how much they can push through it at a
 *  time.
 *
 *  These live HERE and not in exchangeActions because that file is 'use server'
 *  and a 'use server' module silently DROPS every non-async export. Importing
 *  them from there compiled clean and then failed the build with an unreadable
 *  Ecmascript error. */
export const MIN_STAKE = 500
export const MAX_STAKE = 250_000

/** Gate: Fishing at the cap, and nothing else.
 *
 *  Navigation used to be half the requirement, on the reasoning that the
 *  Exchange should ask for both halves of the game. But the Exchange is a
 *  market in FISH, priced off the same board the Hold sells into, and every
 *  read that makes you money here is a read about fish. Asking a captain to
 *  grind voyages for it taxed the wrong skill.
 *
 *  100 is MAX_LEVEL, so this is the last thing fishing gives you: the board
 *  stops being a price list and starts being something you can take a position
 *  on. */
/** THE BOARD IS SHUT WHILE IT IS REBUILT.
 *
 *  The Exchange is being rebuilt on its own free-floating indexes instead of
 *  prices borrowed from the sell market. Until that lands, nothing new can be
 *  opened: every contract written against the old series would have to be
 *  refunded again on the day of the swap, and refunding somebody twice is how a
 *  market loses the only thing it has, which is trust.
 *
 *  Every open contract was already refunded at full stake, so nothing is
 *  stranded behind this. Flip to false when the new board ships. */
export const EXCHANGE_UNDER_CONSTRUCTION = false

export const EXCHANGE_FISHING_LEVEL = 100

// ── How jumpy is it ─────────────────────────────────────────────────────────

/** The spread of a full-term move, as a percentage, for a quoted instrument.
 *
 *  This is the number the board was hiding. A rarity-1 fish moves 0.030 per
 *  tick and a rarity-5 moves 0.075, two and a half times as far, and nothing on
 *  screen said so: two fish at 1.05 looked like the same bet. Leverage encodes
 *  it, but as an output nobody can read backwards.
 *
 *  Derived from sigmaForTerm rather than a second volatility table, so it
 *  cannot disagree with the payouts. Averaged across the two directions because
 *  it describes the instrument, not a side of it, and a player asking "how far
 *  does this thing move" is not asking about their contract yet. */
export function typicalSwingPct(q: { rise: number; fall: number }): number {
  return (sigmaForTerm(q.rise) + sigmaForTerm(q.fall)) / 2
}

export function singleSwingPct(rarity: number, term: Term = 24): number {
  return typicalSwingPct((SINGLE_LEVERAGE[rarity] ?? SINGLE_LEVERAGE[3])[term])
}

export function fundSwingPct(fundId: string, term: Term = 24): number {
  return typicalSwingPct((FUND_LEVERAGE[fundId] ?? FUND_LEVERAGE.sea)[term])
}

/** Plain words for that number, so the board reads without doing arithmetic.
 *  Cut on the day swing: the Sea Index sits near 4.5% and a legendary fish near
 *  21%, and the bands are placed so each says something different about what
 *  you are about to take a position on. */
export function swingLabel(swingPct: number): string {
  if (swingPct < 5) return 'Calm'
  if (swingPct < 9) return 'Steady'
  if (swingPct < 13) return 'Choppy'
  if (swingPct < 18) return 'Rough'
  return 'Wild'
}

/** The PRICE the instrument has to reach for a contract to break even.
 *
 *  Break-even was only ever stated as a percentage while the chart beside it
 *  was drawn in price, leaving the player to convert in their head before
 *  committing doubloons. A Fall contract needs the price DOWN, so its target
 *  sits below the entry. */
export function targetPrice(entry: number, dir: Direction, breakEvenPct: number): number {
  return dir === 'rise' ? entry * (1 + breakEvenPct / 100) : entry * (1 - breakEvenPct / 100)
}
