// SNAPSHOT THE LIVE SCHEMA INTO THE REPO (Steam prep, Phase A step 1, 2026-09-28).
//
// The live database carries logic the repo never had: about 25 of the 35 RPCs
// the game calls, the pg_cron jobs, triggers, views and policies were applied
// straight to the database and exist nowhere else. This writes all of it to
// web/supabase/live/ as plain SQL, in the order it would be rebuilt in, so the
// backend can be recreated from the repo (disaster recovery now, a local
// schema for an offline build later).
//
// Reads through admin_schema_snapshot(), a service-role-only function that
// returns the DDL as text. Changes nothing. Re-run after any schema change:
//
//   npx tsx scripts/snapshot-schema.mts
//
// Not a migration history: it is what is live NOW. The old migrate_*.sql
// files stay as the record of how it got here.

import fs from 'fs'
import path from 'path'

const env = Object.fromEntries(fs.readFileSync(path.join(process.cwd(), '.env.local'), 'utf8')
  .split(/\r?\n/).filter(l => l.includes('=') && !l.startsWith('#'))
  .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^"|"$/g, '')] }))
const URL_ = env.NEXT_PUBLIC_SUPABASE_URL
const KEY = env.SUPABASE_SERVICE_ROLE_KEY
if (!URL_ || !KEY) throw new Error('NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be in .env.local')

type Fn = { name: string; args: string; def: string; grants: string[] }
type Snap = {
  sequences: string[]; tables: string[]; constraints: string[]; indexes: string[]
  functions: Fn[]; views: string[]; triggers: string[]; rls: string[]; policies: string[]
  cron: { name: string; schedule: string; command: string }[]
  extensions: string[]; realtime: string[]; buckets: { id: string; public: boolean }[]
}

const res = await fetch(`${URL_}/rest/v1/rpc/admin_schema_snapshot`, {
  method: 'POST',
  headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, 'content-type': 'application/json' },
  body: '{}',
})
if (!res.ok) throw new Error(`snapshot failed: ${res.status} ${await res.text()}`)
const s = await res.json() as Snap

const dir = path.join(process.cwd(), 'supabase', 'live')
fs.mkdirSync(dir, { recursive: true })
const head = (what: string) => `-- ${what}\n-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;\n-- change the database, then re-run the script.\n\n`
// SECRETS NEVER REACH THE REPO. A job that calls out over HTTP carries its
// bearer token in the command text (reconcile-premium did); it is replaced
// with a placeholder, and the real one stays in the database.
const redact = (t: string) => t
  .replace(/(Bearer\s+)[A-Za-z0-9_\-.]{12,}/g, '$1<REDACTED: set from the live job or Vault>')
  .replace(/((?:api[_-]?key|secret|password)["']?\s*[:=]\s*["'])[^"']{8,}/gi, '$1<REDACTED>')
const write = (file: string, what: string, body: string) => {
  fs.writeFileSync(path.join(dir, file), head(what) + redact(body).trimEnd() + '\n')
  console.log(`${file}: ${body.split('\n').length} lines`)
}

write('00_extensions.sql', 'Extensions', s.extensions.map(e => `create extension if not exists ${JSON.stringify(e)};`).join('\n'))
write('01_sequences.sql', 'Sequences', s.sequences.join('\n'))
write('02_tables.sql', 'Tables (columns, defaults, not-null)', s.tables.join('\n\n'))
write('03_constraints.sql', 'Primary keys, uniques, checks, foreign keys', s.constraints.join('\n'))
write('04_functions.sql', 'Functions, with their EXECUTE grants re-applied',
  s.functions.map(f => {
    const sig = `public.${f.name}(${f.args})`
    const grants = [`revoke all on function ${sig} from public, anon, authenticated;`,
      ...f.grants.filter(g => g !== 'postgres').map(g => `grant execute on function ${sig} to ${g};`)]
    return `${f.def}\n${grants.join('\n')}`
  }).join('\n\n'))
write('05_views.sql', 'Views and materialized views', s.views.map(v => v.trimEnd().replace(/;?$/, ';')).join('\n\n'))
write('06_indexes.sql', 'Indexes not backing a constraint', s.indexes.join('\n'))
write('07_triggers.sql', 'Triggers (public tables and auth.users)', s.triggers.join('\n'))
write('08_rls.sql', 'Row level security and policies', [...s.rls, '', ...s.policies].join('\n'))
write('09_cron.sql', 'pg_cron jobs', s.cron.map(j =>
  `select cron.schedule(${sq(j.name)}, ${sq(j.schedule)}, ${sq(j.command)});`).join('\n'))
write('10_platform.md', 'Supabase platform settings the SQL above does not cover',
  [
    '## Realtime publication (supabase_realtime)', ...s.realtime.map(t => `- ${t}`), '',
    '## Storage buckets', ...s.buckets.map(b => `- ${b.id} (${b.public ? 'public' : 'private'})`), '',
    '## Not captured here', '- Auth settings (magic link, Google OAuth), edge functions deployed only on the platform',
    '  (reconcile-premium), table-level grants (Supabase defaults), Vault secrets.',
  ].join('\n').replace(/^-- .*$/gm, ''))

function sq(t: string) { return `'${t.replace(/'/g, "''")}'` }
