-- Extensions
-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;
-- change the database, then re-run the script.

create extension if not exists "pg_cron";
create extension if not exists "pg_net";
create extension if not exists "pg_stat_statements";
create extension if not exists "pgcrypto";
create extension if not exists "plpgsql";
create extension if not exists "supabase_vault";
create extension if not exists "uuid-ossp";
