-- Tables (columns, defaults, not-null)
-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;
-- change the database, then re-run the script.

create table if not exists public.announcements (
  id uuid default gen_random_uuid() not null,
  message text not null,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.anomaly_flags (
  id bigint default nextval('anomaly_flags_id_seq'::regclass) not null,
  user_id uuid not null,
  kind text not null,
  severity smallint default 1 not null,
  detail jsonb,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.bait_inventory (
  user_id uuid not null,
  bait_type text not null,
  quantity integer default 0 not null
);

create table if not exists public.beta_roster (
  user_id uuid not null,
  username text not null,
  joined_at timestamp with time zone,
  last_active_at timestamp with time zone,
  fishing_xp bigint,
  expedition_xp integer,
  badges integer,
  species integer,
  fish_caught integer,
  raids_cleared integer,
  gauntlet_deepest integer,
  was_premium boolean,
  is_admin boolean,
  snapshot jsonb not null,
  captured_at timestamp with time zone default now() not null
);

create table if not exists public.blackjack_buy_ins (
  id bigint default nextval('blackjack_buy_ins_id_seq'::regclass) not null,
  user_id uuid not null,
  amount integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.blackjack_hands (
  id bigint default nextval('blackjack_hands_id_seq'::regclass) not null,
  user_id uuid not null,
  initial_wager integer not null,
  total_wagered integer not null,
  status text not null,
  state jsonb,
  result jsonb,
  net_delta integer,
  created_at timestamp with time zone default now() not null,
  settled_at timestamp with time zone
);

create table if not exists public.bounty_board_history (
  id bigint not null,
  user_id uuid not null,
  date date not null,
  bounty_ids text[] not null,
  claimed boolean[] not null,
  slots integer not null,
  reroll_used boolean default false not null,
  archived_at timestamp with time zone default now() not null
);

create table if not exists public.bounty_events (
  id bigint not null,
  user_id uuid not null,
  kind text not null,
  value integer default 0 not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.bounty_progress (
  user_id uuid not null,
  date text not null,
  bounty_ids text[] default '{}'::text[] not null,
  baselines jsonb default '{}'::jsonb not null,
  claimed boolean[] default '{}'::boolean[] not null,
  assigned_at timestamp with time zone default now() not null,
  reroll_used boolean default false not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.card_variants (
  id integer default nextval('card_variants_id_seq'::regclass) not null,
  card_id integer,
  variant_name text default ''::text not null,
  border_style text default ''::text not null,
  art_effect text default ''::text not null,
  drop_weight numeric default 1 not null
);

create table if not exists public.cards (
  id integer default nextval('cards_id_seq'::regclass) not null,
  name text not null,
  slug text not null,
  filename text not null,
  tier integer not null,
  created_at timestamp with time zone default now(),
  fish_id integer,
  zone text default 'shallows'::text not null,
  power integer default 0 not null,
  dodge integer default 0 not null,
  fortune integer default 0 not null,
  mythic_power integer default 0 not null,
  mythic_dodge integer default 0 not null,
  mythic_fortune integer default 0 not null
);

create table if not exists public.casino_buy_ins (
  id bigint not null,
  user_id uuid not null,
  amount integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.challenge_overrides (
  date date not null,
  tier1 jsonb not null,
  tier2 jsonb not null,
  tier3 jsonb not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.chart_contests (
  id integer default nextval('chart_contests_id_seq'::regclass) not null,
  name text default 'Chart the Course'::text not null,
  grid_cols integer default 10 not null,
  grid_rows integer default 15 not null,
  start_col integer default 4 not null,
  path jsonb not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  ended_at timestamp with time zone
);

create table if not exists public.chart_guesses (
  id bigint default nextval('chart_guesses_id_seq'::regclass) not null,
  user_id uuid not null,
  contest_id integer not null,
  "row" integer not null,
  col integer not null,
  correct boolean not null,
  guessed_at timestamp with time zone default now() not null
);

create table if not exists public.chart_progress (
  id bigint default nextval('chart_progress_id_seq'::regclass) not null,
  user_id uuid not null,
  contest_id integer not null,
  highest_row integer default '-1'::integer not null,
  moves_used integer default 0 not null,
  completed_at timestamp with time zone,
  ship_color text,
  created_at timestamp with time zone default now() not null,
  path_index integer default 0 not null,
  milestones_awarded integer default 0 not null,
  moves_granted integer default 0 not null,
  last_move_grant_date date
);

create table if not exists public.claim_tokens (
  id integer default nextval('claim_tokens_id_seq'::regclass) not null,
  token text not null,
  email text,
  packs_to_grant integer default 1 not null,
  status text default 'pending'::text not null,
  claimed_by uuid,
  claimed_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

create table if not exists public.contests (
  contest_id text not null,
  winner_user_id uuid not null,
  won_at timestamp with time zone default now() not null,
  prize_code text not null,
  notes text
);

create table if not exists public.crew (
  follower_id uuid not null,
  following_id uuid not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.crew_hall_bunks (
  id bigint not null,
  user_id uuid not null,
  crew_id bigint not null,
  since timestamp with time zone default now() not null,
  created_at timestamp with time zone default now() not null,
  rate_per_hour integer,
  cap_hours integer,
  slot smallint
);

create table if not exists public.daily_challenge_progress (
  user_id uuid not null,
  date text not null,
  p1 integer default 0 not null,
  p2 integer default 0 not null,
  p3 integer default 0 not null,
  claimed_1 boolean default false not null,
  claimed_2 boolean default false not null,
  claimed_3 boolean default false not null,
  fishing_level_snapshot integer,
  claimed_bonus boolean default false not null,
  p4 integer default 0 not null,
  claimed_4 boolean default false not null
);

create table if not exists public.daily_expeditions (
  id integer default nextval('daily_expeditions_id_seq'::regclass) not null,
  expedition_date date not null,
  zone text not null,
  event_sequence jsonb not null
);

create table if not exists public.daily_fish (
  date date not null,
  fish_id integer not null
);

create table if not exists public.daily_fish_attempts (
  id integer default nextval('daily_fish_attempts_id_seq'::regclass) not null,
  user_id uuid not null,
  date date not null,
  guesses jsonb default '[]'::jsonb not null,
  solved boolean default false not null,
  gems_awarded integer default 0 not null,
  created_at timestamp with time zone default now(),
  hints_used jsonb default '{}'::jsonb not null
);

create table if not exists public.daily_fish_generated (
  date date not null,
  common_name text not null,
  scientific_name text,
  clue_1 text not null,
  clue_2 text not null,
  clue_3 text not null,
  clue_4 text not null,
  fun_fact text not null,
  habitat text,
  diet text,
  size text,
  conservation_status text,
  range text,
  created_at timestamp with time zone default now()
);

create table if not exists public.daily_quiz (
  date date not null,
  question text not null,
  options jsonb not null,
  correct_index integer not null,
  explanation text not null,
  topic text,
  created_at timestamp with time zone default now()
);

create table if not exists public.daily_recruits (
  id bigint not null,
  user_id uuid not null,
  recruit_date date default ((now() AT TIME ZONE 'utc'::text))::date not null,
  slot smallint not null,
  source text default 'free'::text not null,
  card_id integer not null,
  rarity smallint not null,
  power integer default 0 not null,
  dodge integer default 0 not null,
  fortune integer default 0 not null,
  effects jsonb default '[]'::jsonb not null,
  recruited boolean default false not null,
  created_at timestamp with time zone default now() not null,
  start_xp integer default 0 not null
);

create table if not exists public.daily_sudoku (
  date date not null,
  puzzles jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.daily_voyages (
  id bigint default nextval('daily_voyages_id_seq'::regclass) not null,
  user_id uuid not null,
  voyage_date date not null,
  crew_variant_ids integer[] not null,
  ship_tier integer default 0 not null,
  status text default 'pending'::text not null,
  events jsonb default '[]'::jsonb not null,
  total_doubloons integer default 0 not null,
  crew_lost integer[] default '{}'::integer[] not null,
  created_at timestamp with time zone default now() not null,
  total_gems integer default 0 not null,
  route text default 'open'::text not null,
  captains_log text,
  log_generated_at timestamp with time zone,
  duration_ms bigint,
  tide_turner_drop boolean default false,
  phantom_hook_drop boolean default false not null,
  xp_bonus_pct numeric default 0 not null,
  perfected_sigil_drop boolean default false not null
);

create table if not exists public.dice_rolls (
  id bigint not null,
  user_id uuid not null,
  symbol text not null,
  wager integer not null,
  result text[] not null,
  matches integer not null,
  payout integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.doubloon_transactions (
  id bigint not null,
  user_id uuid not null,
  amount integer not null,
  reason text not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.exchange_bets (
  id bigint not null,
  user_id uuid not null,
  index_id text not null,
  direction text not null,
  term integer not null,
  distance_pct numeric(8,3) not null,
  multiplier numeric(12,4),
  stake integer not null,
  entry_price numeric(20,8) not null,
  opened_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone not null,
  status text default 'open'::text not null,
  exit_price numeric(20,8),
  payout integer,
  settled_at timestamp with time zone,
  seen boolean default false not null,
  units numeric(20,4),
  strike numeric,
  premium_each numeric,
  lot integer default 1 not null
);

create table if not exists public.exchange_indexes (
  id text not null,
  family text not null,
  name text not null,
  blurb text default ''::text not null,
  accent text default '#7dd3fc'::text not null,
  vol numeric not null,
  beta numeric not null,
  price numeric(20,8) default 1.0 not null,
  prev_price numeric(20,8) default 1.0 not null,
  trend numeric default 0 not null,
  trend_ticks integer default 0 not null,
  history jsonb default '[]'::jsonb not null,
  updated_at timestamp with time zone default now() not null,
  sort integer default 0 not null,
  base_price numeric(20,8) default 1.0 not null,
  last_event_at timestamp with time zone,
  last_event text,
  last_event_pct numeric,
  next_event_at timestamp with time zone,
  next_event_label text
);

create table if not exists public.expedition_items (
  id bigint not null,
  user_id uuid not null,
  item_id text not null,
  quantity integer default 1 not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.expeditions (
  id integer default nextval('expeditions_id_seq'::regclass) not null,
  user_id uuid,
  zone text not null,
  ship_tier integer not null,
  status text default 'active'::text,
  current_node integer default 0,
  events jsonb default '[]'::jsonb,
  crew_loadout jsonb default '{}'::jsonb not null,
  loot jsonb default '{}'::jsonb,
  hull_damage integer default 0,
  expedition_date date default CURRENT_DATE not null,
  started_at timestamp with time zone default now(),
  completed_at timestamp with time zone,
  combat_state jsonb,
  equipped_item text,
  run_buffs jsonb default '[]'::jsonb,
  run_gold integer default 0 not null,
  captains_log text,
  log_generated_at timestamp with time zone
);

create table if not exists public.fish (
  id integer default nextval('fish_id_seq'::regclass) not null,
  common_name text not null,
  scientific_name text,
  slug text not null,
  depth_zone text,
  depth_min_m integer,
  depth_max_m integer,
  size_description text,
  diet text,
  lifespan text,
  fun_fact text,
  clue_1 text not null,
  clue_2 text not null,
  clue_3 text not null,
  clue_4 text not null,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.fish_collection (
  user_id uuid not null,
  fish_id integer not null,
  catch_count integer default 1 not null,
  first_caught_at timestamp with time zone default now() not null,
  last_caught_at timestamp with time zone default now() not null,
  is_golden boolean default false not null
);

create table if not exists public.fish_inventory (
  user_id uuid not null,
  fish_id integer not null,
  quantity integer default 0 not null
);

create table if not exists public.fish_lifetime (
  user_id uuid not null,
  fish_id integer not null,
  catches integer default 0 not null,
  first_caught_at timestamp with time zone,
  last_caught_at timestamp with time zone
);

create table if not exists public.fish_market (
  fish_id integer not null,
  multiplier numeric(4,2) default 1.00 not null,
  prev_multiplier numeric(4,2) default 1.00 not null,
  history jsonb default '[]'::jsonb not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fish_personal_bests (
  id bigint default nextval('fish_personal_bests_id_seq'::regclass) not null,
  user_id uuid not null,
  fish_id integer not null,
  best_length_in numeric not null,
  caught_at timestamp with time zone default now() not null
);

create table if not exists public.fish_species (
  id integer default nextval('fish_species_id_seq'::regclass) not null,
  name text not null,
  scientific_name text not null,
  description text,
  fun_fact text not null,
  habitat text not null,
  bite_rarity integer not null,
  catch_difficulty integer not null,
  sort_order integer default 0 not null,
  sell_value integer default 0 not null,
  catch_score integer default 50 not null,
  habitat_type text,
  size_category text,
  diet_type text,
  fish_group text,
  fotd_eligible boolean default false not null,
  water_type text,
  region text,
  is_edible boolean,
  length_min_in numeric,
  length_max_in numeric,
  fotd_family text
);

create table if not exists public.gauntlet_depth_bests (
  user_id uuid not null,
  variant text not null,
  hardcore boolean not null,
  depth integer not null,
  best_ms integer not null,
  achieved_at timestamp with time zone default now() not null
);

create table if not exists public.gauntlet_runs (
  id bigint not null,
  user_id uuid not null,
  variant text default 'davy'::text not null,
  hardcore boolean default false not null,
  depth integer default 0 not null,
  duration_ms integer default 0 not null,
  outcome text not null,
  ended_at timestamp with time zone default now() not null
);

create table if not exists public.gem_transactions (
  id bigint default nextval('gem_transactions_id_seq'::regclass) not null,
  user_id uuid not null,
  amount integer not null,
  reason text not null,
  created_at timestamp with time zone default now() not null,
  payment_ref text
);

create table if not exists public.homesteads (
  user_id uuid not null,
  house integer default 0 not null,
  portal integer default 0 not null,
  gallery integer default 0 not null,
  furniture jsonb default '{}'::jsonb not null,
  pinned text[] default '{}'::text[] not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  owned text[] default '{}'::text[] not null,
  dock integer default 0 not null,
  garden integer default 0 not null,
  beacon integer default 0 not null,
  layout jsonb,
  name text
);

create table if not exists public.mail_messages (
  id uuid default gen_random_uuid() not null,
  subject text not null,
  body text not null,
  sender_label text default 'Cap''n Shibling'::text not null,
  attachment_doubloons integer default 0 not null,
  attachment_gems integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone,
  target_user_id uuid,
  image_url text,
  evergreen boolean default false not null
);

create table if not exists public.mail_reads (
  user_id uuid not null,
  message_id uuid not null,
  read_at timestamp with time zone default now() not null,
  claimed_at timestamp with time zone
);

create table if not exists public.market_state (
  id integer default 1 not null,
  mood text default 'calm'::text not null,
  mood_bias numeric(5,3) default 0 not null,
  mood_expires_at timestamp with time zone,
  next_update_at timestamp with time zone default (date_trunc('hour'::text, now()) + '01:00:00'::interval) not null,
  exchange_cycle bigint default 0 not null
);

create table if not exists public.minefield_attempts (
  user_id uuid not null,
  week date not null,
  revealed jsonb default '[]'::jsonb not null,
  flagged jsonb default '[]'::jsonb not null,
  status text default 'active'::text not null,
  points_awarded integer default 0 not null,
  busts integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.minefield_boards (
  week date not null,
  layout jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.pack_history (
  id bigint default nextval('pack_history_id_seq'::regclass) not null,
  user_id uuid not null,
  opened_at timestamp with time zone default now() not null,
  cards jsonb not null,
  was_god_pack boolean default false not null
);

create table if not exists public.pending_sales (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  amount integer not null,
  fish_count integer default 0 not null,
  reason text not null,
  settles_at timestamp with time zone not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.prize_claims (
  id integer default nextval('prize_claims_id_seq'::regclass) not null,
  user_id uuid,
  prize_code text not null,
  card_variant_id integer,
  card_name text not null,
  variant_name text not null,
  claimed_at timestamp with time zone default now(),
  fulfilled boolean default false
);

create table if not exists public.profiles (
  id uuid not null,
  username text not null,
  packs_available integer default 0,
  created_at timestamp with time zone default now(),
  packs_since_legendary integer default 0 not null,
  doubloons integer default 100 not null,
  last_daily_claim date,
  fotd_streak integer default 0 not null,
  fotd_longest_streak integer default 0 not null,
  last_fotd_date date,
  highest_rank_claimed integer default 0,
  hook_tier integer default 0 not null,
  username_changed boolean default false,
  showcase_variant_ids bigint[],
  is_premium boolean default false,
  premium_expires_at timestamp with time zone,
  ship_tier integer default 2 not null,
  last_ship_claim date,
  last_pack_claim date,
  last_viewed_achievements_at timestamp with time zone,
  fishing_date date,
  fishing_casts integer default 0 not null,
  has_seen_welcome boolean default false,
  fishing_abyss_streak integer default 0,
  rod_tier integer default 0 not null,
  reel_tier integer default 0 not null,
  line_tier integer default 0 not null,
  bait_last_topup date,
  gems integer default 0 not null,
  fishing_xp bigint default 0 not null,
  saved_crew jsonb default '[]'::jsonb,
  highest_perfect_streak integer default 0 not null,
  has_seen_fotd_intro boolean default false not null,
  has_seen_packs_intro boolean default false not null,
  has_seen_market_intro boolean default false not null,
  has_seen_fishing_tour boolean default false not null,
  has_seen_fishing_catch_tour boolean default false not null,
  last_worm_claim date,
  highest_streak_set_at timestamp with time zone,
  zone_shallows_rewarded boolean default false not null,
  zone_open_waters_rewarded boolean default false not null,
  zone_deep_rewarded boolean default false not null,
  zone_abyss_rewarded boolean default false not null,
  ring_skin text default 'standard'::text not null,
  unlocked_ring_skins text[] default '{}'::text[] not null,
  best_streak_zone text,
  ship_name text,
  expedition_xp integer default 0 not null,
  is_admin boolean default false not null,
  ship_color text,
  has_tide_turner boolean default false,
  tide_turner_used integer default 0,
  tide_turner_date date,
  equipped_special text,
  has_phantom_hook boolean default false not null,
  ship_skins text[] default '{}'::text[],
  equipped_ship_skin text,
  raid_items text[] default '{}'::text[],
  equipped_raid_items text[] default '{}'::text[],
  has_seen_raid_tutorial boolean default false,
  prestige_levels jsonb default '{}'::jsonb,
  ancient_catches integer[] default '{}'::integer[],
  has_auto_caster boolean default false,
  character_color text default 'default'::text not null,
  unlocked_character_colors text[] default '{}'::text[],
  has_seen_setup boolean default false,
  has_completed_practice_raid boolean default false,
  active_event jsonb,
  last_event_at timestamp with time zone,
  unlocked_badges text[] default '{}'::text[] not null,
  equipped_badges text[] default '{}'::text[] not null,
  fish_hold_tier integer default 0 not null,
  equipped_boat text,
  unlocked_boats text[] default ARRAY[]::text[],
  unlocked_hats text[] default '{}'::text[],
  equipped_hat text,
  avatar_bg_color text,
  avatar_border_color text,
  has_seen_expeditions_tour boolean default false not null,
  finn_encounters integer default 0 not null,
  finn_wins integer default 0 not null,
  finn_seen_beats text[] default '{}'::text[] not null,
  finn_revealed boolean default false not null,
  finn_last_outcome text,
  has_seen_market_tour boolean default false not null,
  raid_node_progress jsonb default '{}'::jsonb not null,
  raid_repair_owed integer default 0 not null,
  equipped_repair_kit text default 'basic_repair_kit'::text not null,
  owned_repair_kits text[] default ARRAY['basic_repair_kit'::text] not null,
  last_used_bait text,
  unlocked_avatar_specials text[] default '{}'::text[],
  profile_bg text,
  total_perfects integer default 0 not null,
  highest_raid_damage integer default 0 not null,
  fishing_jackpots integer default 0 not null,
  fishing_double_catches integer default 0 not null,
  fishing_snags integer default 0 not null,
  fishing_crates_opened integer default 0 not null,
  last_free_recruit_date date,
  showcase_crew_ids jsonb default '[]'::jsonb not null,
  lifetime_recruits integer default 0 not null,
  last_seen_at timestamp with time zone,
  current_perfect_streak integer default 0 not null,
  catch_pending boolean default false not null,
  ship_classes jsonb default '{}'::jsonb not null,
  seen_chapter_unlocks text[] default '{}'::text[] not null,
  force_shiny_next_perfect boolean default false not null,
  force_shiny_always boolean default false not null,
  has_seen_first_catch_celebration boolean default false not null,
  unlocked_pets text[] default '{}'::text[] not null,
  equipped_pet text,
  blackjack_chips integer default 0 not null,
  blackjack_session_buy_ins integer default 0 not null,
  show_wait_timer boolean default true not null,
  roulette_chips integer default 0 not null,
  roulette_session_buy_ins integer default 0 not null,
  has_perfected_sigil boolean default false not null,
  crew_hall_tier integer default 1 not null,
  casino_chips integer default 0 not null,
  casino_session_buy_ins integer default 0 not null,
  blackjack_session_net integer default 0 not null,
  roulette_session_net integer default 0 not null,
  slots_session_net integer default 0 not null,
  puzzle_points integer default 0 not null,
  gauntlet_last_date date,
  gauntlet_run_open boolean default false not null,
  gauntlet_deepest integer default 0 not null,
  last_crate_claim_week date,
  has_auto_catcher boolean default false not null,
  pending_reroll jsonb,
  pvp_wins integer default 0 not null,
  pvp_losses integer default 0 not null,
  last_active_at timestamp with time zone,
  completionist_effects integer[] default '{}'::integer[] not null,
  has_seen_forge_flourish boolean default false not null,
  gauntlet_last_run_at timestamp with time zone,
  gauntlet_upgrades text[] default '{}'::text[] not null,
  has_seen_gauntlet_intro boolean default false not null,
  gauntlet_best_depth integer default 0 not null,
  gauntlet_best_depth_ms bigint,
  gauntlet_best_depth_at timestamp with time zone,
  gauntlet_fathoms integer default 0 not null,
  claimed_badge_rewards text[] default '{}'::text[] not null,
  trawls_collected integer default 0 not null,
  blackjack_win_streak integer default 0 not null,
  blackjack_dealer_bj_streak integer default 0 not null,
  slots_force_next text,
  gauntlet_contest_depth integer default 0 not null,
  gauntlet_contest_depth_at timestamp with time zone,
  has_seen_contests boolean default false not null,
  gauntlet_big_hit integer default 0 not null,
  gauntlet_big_hit_at timestamp with time zone,
  gauntlet_deepest_run jsonb,
  manowar_augment text,
  gauntlet_confluences_seen text[] default '{}'::text[] not null,
  gauntlet_run_state jsonb,
  gauntlet_resumes_used integer default 0 not null,
  forge_recipes_learned text[] default '{}'::text[] not null,
  has_seen_forge_intro boolean default false not null,
  manowar_augment_build jsonb,
  seen_ultimate_unlock boolean default false not null,
  gauntlet_runs_completed integer default 0 not null,
  gauntlet_fathoms_earned integer default 0 not null,
  gauntlet_max_hit integer default 0 not null,
  gauntlet_deepest_died integer default 0 not null,
  gauntlet_run_hardcore boolean default false not null,
  gauntlet_hc_squad bigint[],
  gauntlet_hc_deepest integer default 0 not null,
  gauntlet_hc_best_depth integer,
  gauntlet_hc_best_depth_ms integer,
  gauntlet_hc_best_depth_at timestamp with time zone,
  gauntlet_hc_deepest_died integer default 0 not null,
  gauntlet_hc_last_run_at timestamp with time zone,
  fishing_renown_alloc jsonb default '{}'::jsonb not null,
  nav_renown_alloc jsonb default '{}'::jsonb not null,
  seen_fishing_renown_intro boolean default false not null,
  seen_nav_renown_intro boolean default false not null,
  discovered_coelacanth boolean default false not null,
  owned_crew_skins jsonb default '[]'::jsonb not null,
  equipped_crew_skins jsonb default '{}'::jsonb not null,
  trophy_size_catches integer default 0 not null,
  blood_gems integer default 0 not null,
  gauntlet_hc_runs_today integer default 0 not null,
  blood_gems_earned integer default 0 not null,
  gauntlet_hc_deepest_run jsonb,
  manowar_schematics boolean default false not null,
  has_sixth_berth boolean default false not null,
  gauntlet_run_terms jsonb,
  gauntlet_hc_best_pressure integer default 0 not null,
  gauntlet_run_offer jsonb,
  claimed_fishing_levels integer default 1 not null,
  captains_orders_done boolean default false not null,
  gauntlet_run_paused boolean default false not null,
  legendary_unlocks text[] default '{}'::text[] not null,
  gauntlet_upgrades_off jsonb default '[]'::jsonb not null,
  pending_cast jsonb,
  has_armory_expansion boolean default false not null,
  has_ancient_deep_access boolean default false not null,
  gauntlet_run_variant text,
  dons_gauntlet_deepest integer default 0 not null,
  dons_gauntlet_best_depth integer default 0 not null,
  dons_gauntlet_best_depth_ms integer,
  dons_gauntlet_best_depth_at timestamp with time zone,
  dons_gauntlet_deepest_run jsonb,
  dons_gauntlet_deepest_died integer default 0 not null,
  dons_gauntlet_runs_completed integer default 0 not null,
  dons_gauntlet_upgrades text[] default '{}'::text[] not null,
  dons_gauntlet_upgrades_off text[] default '{}'::text[] not null,
  dons_stipend_claimed_at timestamp with time zone,
  has_seen_check_tutorial boolean default false not null,
  gauntlet_last_run jsonb,
  dons_gauntlet_last_run jsonb,
  gauntlet_hc_last_run jsonb,
  charting_landmarks_claimed integer[] default '{}'::integer[] not null,
  has_seen_dons_gauntlet_intro boolean default false not null,
  zone_golden_boost jsonb default '{}'::jsonb not null,
  fish_sold_doubloons bigint default 0 not null,
  parlor_streak integer default 0 not null,
  parlor_best_streak integer default 0 not null,
  parlor_rank_gems_awarded integer default 0 not null,
  parlor_points integer default 0 not null,
  current_streak_zone text,
  abyssal_conversion jsonb,
  has_seen_crew_guide boolean default false not null,
  has_seen_ship_guide boolean default false not null,
  has_seen_den_guide boolean default false not null,
  has_seen_parlor_guide boolean default false not null,
  has_seen_charting_guide boolean default false not null,
  lifetime_species jsonb default '[]'::jsonb not null,
  lifetime_species_count integer generated always as (jsonb_array_length(lifetime_species)) stored,
  finn_spoil_free text,
  finn_spoil_paid text,
  equipped_special_2 text,
  has_anglers_patience boolean default false not null,
  anglers_patience_xp bigint default 0 not null,
  borrowed_jaw_xp bigint default 0 not null,
  crew_drill_level integer default 1 not null,
  crew_bunks_bought integer default 0 not null,
  crew_stores_level integer default 1 not null,
  dons_gauntlet_hc_deepest integer default 0 not null,
  dons_gauntlet_hc_deepest_died integer default 0 not null,
  dons_gauntlet_hc_deepest_run jsonb,
  dons_gauntlet_hc_last_run jsonb,
  dons_gauntlet_hc_last_run_at timestamp with time zone,
  dons_gauntlet_hc_runs_today integer default 0 not null,
  dons_gauntlet_hc_best_depth integer default 0 not null,
  dons_gauntlet_hc_best_depth_ms integer,
  dons_gauntlet_hc_best_depth_at timestamp with time zone,
  dons_gauntlet_hc_best_pressure integer default 0 not null,
  dons_gauntlet_hc_squad bigint[],
  daily_challenge_sweeps integer default 0 not null,
  daily_master_cleared integer default 0 not null,
  voyage_booty_hauls integer default 0 not null,
  crate_opens jsonb default '{}'::jsonb not null,
  bait_used jsonb default '{}'::jsonb not null,
  biggest_fish_sale integer default 0 not null,
  fish_sold_count integer default 0 not null,
  has_seen_fishing_hub_tour boolean default false not null,
  has_seen_exchange_intro boolean default false not null,
  bounty_rung_seen integer default 0 not null,
  bounties_claimed integer default 0 not null,
  bounty_gems_earned integer default 0 not null,
  bounty_boards_cleared integer default 0 not null,
  bounty_elites_claimed integer default 0 not null,
  bounty_points integer default 0 not null,
  bounty_milestones_claimed integer default 0 not null,
  exchange_watchlist text[] default '{}'::text[] not null,
  crew_next_roll_legendary boolean default false not null,
  renown_respecs integer default 0 not null,
  crew_next_roll_legendary_slug text,
  gauntlet_run_active_ms integer default 0 not null,
  gauntlet_run_tick_at timestamp with time zone,
  ancient_vigil jsonb default '{}'::jsonb not null,
  equipped_pet_bow text,
  badge_unlocked_at jsonb default '{}'::jsonb not null,
  ship_refits_used integer default 0 not null,
  rod_rack_tier integer default 0 not null,
  hull_speed_tier integer default 0 not null,
  rods_aboard integer[] default '{}'::integer[] not null,
  sea_x double precision,
  sea_y double precision,
  sea_explored text,
  hull_handling_tier smallint default 0 not null,
  hull_accel_tier smallint default 0 not null,
  sea_seen_at timestamp with time zone,
  finn_challenge jsonb,
  has_seen_sea_tour boolean default false not null,
  sea_hints_seen text[] default '{}'::text[] not null,
  auto_fishing_on boolean default false not null,
  sea_side text default 'fishing'::text not null,
  portal_tier smallint default 1 not null,
  portal_components_spent integer default 0 not null,
  finn_quest jsonb,
  finn_quests_done text[] default '{}'::text[] not null,
  zone_perfects jsonb default '{}'::jsonb not null,
  sea_tour_step smallint default 0 not null,
  lantern_tier integer default 0 not null,
  portal_ports text[] default '{}'::text[] not null,
  sea_explored_exp text,
  has_seen_gate_tour boolean default false not null,
  gate_tour_step integer default 0 not null,
  almanac_viewed_at timestamp with time zone,
  frozen boolean default false not null,
  sea_session text,
  has_seen_skirmish_tour boolean default false not null,
  seen_unlocks text[],
  seen_promotions text[],
  last_recall_fish_at timestamp with time zone,
  last_recall_exp_at timestamp with time zone,
  full_days integer default 0 not null,
  last_full_day date,
  recruits_seen_on date
);

create table if not exists public.quiz_answers (
  user_id uuid not null,
  date date not null,
  chosen_index integer not null,
  correct boolean not null,
  reward integer default 0 not null,
  answered_at timestamp with time zone default now()
);

create table if not exists public.raid_completions (
  id bigint default nextval('raid_completions_id_seq'::regclass) not null,
  user_id uuid not null,
  elapsed_ms integer not null,
  completed_at timestamp with time zone default now() not null,
  raid_id text default 'corsairs_reckoning'::text not null
);

create table if not exists public.rate_limits (
  key text not null,
  count integer default 1 not null,
  window_start timestamp with time zone default now() not null
);

create table if not exists public.redemption_codes (
  id integer default nextval('redemption_codes_id_seq'::regclass) not null,
  code text not null,
  redeemed_by uuid,
  redeemed_at timestamp with time zone,
  packs_granted integer default 1
);

create table if not exists public.rigging_attempts (
  user_id uuid not null,
  week date not null,
  paths jsonb default '{}'::jsonb not null,
  status text default 'active'::text not null,
  points_awarded integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.rigging_boards (
  week date not null,
  layout jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.rod_inventory (
  user_id uuid not null,
  rod_tier integer not null,
  purchased_at timestamp with time zone default now(),
  quantity integer default 1 not null
);

create table if not exists public.roulette_buy_ins (
  id bigint default nextval('roulette_buy_ins_id_seq'::regclass) not null,
  user_id uuid not null,
  amount integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.roulette_spins (
  id bigint default nextval('roulette_spins_id_seq'::regclass) not null,
  user_id uuid not null,
  bets jsonb not null,
  winning_number integer not null,
  total_wagered integer not null,
  total_payout integer not null,
  net_chips integer not null,
  chips_before integer not null,
  chips_after integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.run_tokens (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  kind text not null,
  meta jsonb,
  kills integer default 0 not null,
  issued_at timestamp with time zone default now() not null,
  consumed_at timestamp with time zone,
  expires_at timestamp with time zone default (now() + '06:00:00'::interval) not null,
  cleared_at timestamp with time zone,
  paid_rounds integer[] default '{}'::integer[] not null,
  looted_at timestamp with time zone
);

create table if not exists public.sea_digs (
  id bigint not null,
  user_id uuid not null,
  site_id text not null,
  bearing_at timestamp with time zone default now() not null,
  dug_at timestamp with time zone
);

create table if not exists public.sea_discoveries (
  id bigint not null,
  user_id uuid not null,
  isle_id text not null,
  found_at timestamp with time zone default now() not null
);

create table if not exists public.sea_pacts (
  id bigint not null,
  requester_id uuid not null,
  addressee_id uuid not null,
  status text default 'pending'::text not null,
  created_at timestamp with time zone default now() not null,
  responded_at timestamp with time zone
);

create table if not exists public.sea_rapport (
  user_id uuid not null,
  folk_id text not null,
  points integer default 0 not null,
  seen_lines text[] default '{}'::text[] not null,
  last_chat_on text,
  last_gift_on text,
  gifts_given integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  want_fish_id integer,
  want_asked_at timestamp with time zone
);

create table if not exists public.sea_trader_deals (
  user_id uuid not null,
  trader_key text not null,
  sea_day integer not null,
  kind text not null,
  detail jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.shiny_catches (
  id bigint default nextval('shiny_catches_id_seq'::regclass) not null,
  user_id uuid not null,
  fish_id integer not null,
  size_in numeric,
  caught_at timestamp with time zone default now() not null,
  status text default 'hold'::text not null,
  sold_at timestamp with time zone,
  sold_for integer
);

create table if not exists public.ship_battles (
  id uuid default gen_random_uuid() not null,
  challenger_id uuid not null,
  opponent_id uuid not null,
  challenger_username text not null,
  opponent_username text not null,
  status text default 'pending'::text not null,
  challenger_loadout jsonb,
  opponent_loadout jsonb,
  challenger_hp integer default 0 not null,
  opponent_hp integer default 0 not null,
  challenger_charges integer default 0 not null,
  opponent_charges integer default 0 not null,
  round integer default 0 not null,
  challenger_move jsonb,
  opponent_move jsonb,
  rounds jsonb default '[]'::jsonb not null,
  current_round_started_at timestamp with time zone,
  winner_id uuid,
  created_at timestamp with time zone default now() not null,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone default (now() + '7 days'::interval) not null,
  challenger_fx jsonb default '{}'::jsonb not null,
  opponent_fx jsonb default '{}'::jsonb not null
);

create table if not exists public.slot_spins (
  id bigint default nextval('slot_spins_id_seq'::regclass) not null,
  user_id uuid not null,
  wager integer default 0 not null,
  reels text[] not null,
  outcome text not null,
  payout integer default 0 not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.slots_jackpot (
  id integer default 1 not null,
  pot integer default 5000 not null,
  seed integer default 5000 not null,
  last_winner_id uuid,
  last_winner_name text,
  last_win_amount integer,
  last_won_at timestamp with time zone,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.sudoku_attempts (
  user_id uuid not null,
  date date not null,
  progress jsonb default '{}'::jsonb not null,
  solved jsonb default '{}'::jsonb not null,
  doubloons_awarded integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  locked_difficulty text
);

create table if not exists public.trawls (
  id bigint not null,
  user_id uuid not null,
  zone text not null,
  crew_id bigint not null,
  started_at timestamp with time zone default now() not null,
  ends_at timestamp with time zone not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.treasure_match_attempts (
  user_id uuid not null,
  week date not null,
  status text default 'active'::text not null,
  best_score integer default 0 not null,
  points_awarded integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.treasure_match_boards (
  week date not null,
  config jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.trivia_board_attempts (
  user_id uuid not null,
  date date not null,
  answers jsonb default '{}'::jsonb not null,
  gems_awarded integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  category text,
  doubloons_awarded integer default 0 not null
);

create table if not exists public.trivia_boards (
  date date not null,
  board jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.trivia_capstan (
  date date not null,
  puzzles jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.trivia_capstan_attempts (
  user_id uuid not null,
  date date not null,
  runs jsonb default '{}'::jsonb not null,
  doubloons_awarded integer default 0 not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.trivia_ladder_attempts (
  user_id uuid not null,
  date date not null,
  rung integer default 0 not null,
  status text default 'active'::text not null,
  fifty jsonb,
  doubloons_awarded integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  gems_awarded integer default 0 not null,
  current_started_at timestamp with time zone
);

create table if not exists public.trivia_ladders (
  date date not null,
  ladder jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.user_achievements (
  user_id uuid not null,
  achievement_key text not null,
  unlocked_at timestamp with time zone default now() not null
);

create table if not exists public.user_collection (
  id integer default nextval('user_collection_id_seq'::regclass) not null,
  user_id uuid,
  card_variant_id integer,
  obtained_at timestamp with time zone default now()
);

create table if not exists public.user_crew (
  id bigint not null,
  user_id uuid not null,
  card_id integer not null,
  rarity smallint not null,
  power integer default 0 not null,
  dodge integer default 0 not null,
  fortune integer default 0 not null,
  effects jsonb default '[]'::jsonb not null,
  recruited_at timestamp with time zone default now() not null,
  died_at timestamp with time zone,
  died_on_voyage_id bigint,
  xp integer default 0 not null,
  voyage_slot integer,
  raid_slot integer,
  assigned_slot integer,
  nickname text,
  died_hardcore_depth integer,
  trait_offer text,
  pending_trait text
);

create table if not exists public.weekly_bounties (
  week_start date not null,
  shallows_fish_id integer not null,
  open_waters_fish_id integer not null,
  deep_fish_id integer not null,
  abyss_fish_id integer not null
);

create table if not exists public.weekly_bounty_progress (
  user_id uuid not null,
  week_start date not null,
  shallows_completed boolean default false not null,
  open_waters_completed boolean default false not null,
  deep_completed boolean default false not null,
  abyss_completed boolean default false not null,
  shallows_claimed_at timestamp with time zone,
  open_waters_claimed_at timestamp with time zone,
  deep_claimed_at timestamp with time zone,
  abyss_claimed_at timestamp with time zone
);
