-- Functions, with their EXECUTE grants re-applied
-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;
-- change the database, then re-run the script.

CREATE OR REPLACE FUNCTION public.admin_export_player_rows(uid uuid, tbls jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
declare
  t jsonb;
  rows jsonb;
  out jsonb := '{}'::jsonb;
begin
  for t in select * from jsonb_array_elements(tbls) loop
    if to_regclass('public.' || quote_ident(t->>'table')) is null then
      raise exception 'unknown table %', t->>'table';
    end if;
    execute format('select coalesce(jsonb_agg(to_jsonb(x)), ''[]''::jsonb) from public.%I x where x.%I = $1',
      t->>'table', t->>'col') into rows using uid;
    out := out || jsonb_build_object(t->>'table', rows);
  end loop;
  return out;
end
$function$
;
revoke all on function public.admin_export_player_rows(uid uuid, tbls jsonb) from public, anon, authenticated;
grant execute on function public.admin_export_player_rows(uid uuid, tbls jsonb) to service_role;

CREATE OR REPLACE FUNCTION public.admin_import_player_rows(uid uuid, profile jsonb, tbls jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
declare
  t jsonb;
  cols text;
  sets text;
  n int;
  report jsonb := '{}'::jsonb;
  i int;
begin
  for t in select * from jsonb_array_elements(tbls) loop
    if to_regclass('public.' || quote_ident(t->>'table')) is null then
      raise exception 'unknown table %', t->>'table';
    end if;
  end loop;

  for i in reverse jsonb_array_length(tbls) - 1 .. 0 loop
    t := tbls->i;
    execute format('delete from public.%I where %I = $1', t->>'table', t->>'col') using uid;
  end loop;

  if profile is not null then
    select string_agg(format('%I = r.%I', a.attname, a.attname), ', ')
      into sets
      from pg_attribute a
      where a.attrelid = 'public.profiles'::regclass and a.attnum > 0 and not a.attisdropped
        and a.attgenerated = '' and a.attname <> 'id' and profile ? a.attname;
    if sets is not null then
      execute format('update public.profiles p set %s from jsonb_populate_record(null::public.profiles, $1) r where p.id = $2', sets)
        using profile, uid;
    end if;
  end if;

  for i in 0 .. jsonb_array_length(tbls) - 1 loop
    t := tbls->i;
    if jsonb_array_length(coalesce(t->'rows', '[]'::jsonb)) = 0 then
      report := report || jsonb_build_object(t->>'table', 0);
      continue;
    end if;
    select string_agg(quote_ident(a.attname), ', ' order by a.attnum)
      into cols
      from pg_attribute a
      where a.attrelid = ('public.' || quote_ident(t->>'table'))::regclass and a.attnum > 0 and not a.attisdropped
        and a.attgenerated = '' and (t->'rows'->0) ? a.attname;
    -- OVERRIDING SYSTEM VALUE: rows keep their original ids, including in
    -- tables whose id is GENERATED ALWAYS AS IDENTITY.
    execute format(
      'insert into public.%I (%s) overriding system value select %s from jsonb_populate_recordset(null::public.%I, (select jsonb_agg(e || jsonb_build_object(%L, $1)) from jsonb_array_elements($2) e))',
      t->>'table', cols, cols, t->>'table', t->>'col')
      using uid, t->'rows';
    get diagnostics n = row_count;
    report := report || jsonb_build_object(t->>'table', n);
  end loop;
  return report;
end
$function$
;
revoke all on function public.admin_import_player_rows(uid uuid, profile jsonb, tbls jsonb) from public, anon, authenticated;
grant execute on function public.admin_import_player_rows(uid uuid, profile jsonb, tbls jsonb) to service_role;

CREATE OR REPLACE FUNCTION public.admin_schema_snapshot()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
declare
  out jsonb := '{}'::jsonb;
begin
  -- sequences
  out := out || jsonb_build_object('sequences', coalesce((
    select jsonb_agg(format('create sequence if not exists public.%I;', c.relname) order by c.relname)
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'S'), '[]'::jsonb));

  -- tables
  out := out || jsonb_build_object('tables', coalesce((
    select jsonb_agg(ddl order by name) from (
      select c.relname as name,
        format(E'create table if not exists public.%I (\n%s\n);', c.relname,
          string_agg(
            format('  %I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
              case
                when a.attgenerated = 's' then format(' generated always as (%s) stored', pg_get_expr(d.adbin, d.adrelid))
                when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid)
                else '' end,
              case when a.attnotnull then ' not null' else '' end),
            E',\n' order by a.attnum)) as ddl
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
      left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
      where n.nspname = 'public' and c.relkind in ('r', 'p')
      group by c.relname) t), '[]'::jsonb));

  -- constraints
  out := out || jsonb_build_object('constraints', coalesce((
    select jsonb_agg(format('alter table public.%I add constraint %I %s;', c.relname, con.conname, pg_get_constraintdef(con.oid))
      order by c.relname, case con.contype when 'p' then 0 when 'u' then 1 when 'c' then 2 else 3 end, con.conname)
    from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'), '[]'::jsonb));

  -- indexes not backing a constraint
  out := out || jsonb_build_object('indexes', coalesce((
    select jsonb_agg(i.indexdef || ';' order by i.tablename, i.indexname)
    from pg_indexes i
    where i.schemaname = 'public'
      and not exists (select 1 from pg_constraint con where con.conname = i.indexname)), '[]'::jsonb));

  -- functions (not extension-owned)
  out := out || jsonb_build_object('functions', coalesce((
    select jsonb_agg(jsonb_build_object('name', p.proname, 'args', pg_get_function_identity_arguments(p.oid),
      'def', pg_get_functiondef(p.oid) || ';',
      'grants', coalesce((select jsonb_agg(distinct case when x.grantee = 0 then 'public' else x.grantee::regrole::text end)
        from aclexplode(p.proacl) x where x.privilege_type = 'EXECUTE'), '[]'::jsonb))
      order by p.proname, pg_get_function_identity_arguments(p.oid))
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prokind in ('f', 'p')
      and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')), '[]'::jsonb));

  -- views and materialized views
  out := out || jsonb_build_object('views', coalesce((
    select jsonb_agg(case c.relkind
        when 'm' then format(E'create materialized view if not exists public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true))
        else format(E'create or replace view public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true)) end
      order by c.relname)
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind in ('v', 'm')), '[]'::jsonb));

  -- triggers (public tables, and auth.users)
  out := out || jsonb_build_object('triggers', coalesce((
    select jsonb_agg(pg_get_triggerdef(t.oid) || ';' order by c.relname, t.tgname)
    from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
    where not t.tgisinternal and (n.nspname = 'public' or (n.nspname = 'auth' and c.relname = 'users'))), '[]'::jsonb));

  -- row level security and policies
  out := out || jsonb_build_object('rls', coalesce((
    select jsonb_agg(format('alter table public.%I enable row level security;', c.relname) order by c.relname)
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity), '[]'::jsonb));
  out := out || jsonb_build_object('policies', coalesce((
    select jsonb_agg(format('create policy %I on public.%I as %s for %s to %s%s%s;',
        p.policyname, p.tablename, p.permissive, p.cmd, array_to_string(p.roles, ', '),
        case when p.qual is not null then ' using (' || p.qual || ')' else '' end,
        case when p.with_check is not null then ' with check (' || p.with_check || ')' else '' end)
      order by p.tablename, p.policyname)
    from pg_policies p where p.schemaname = 'public'), '[]'::jsonb));

  -- scheduled jobs
  out := out || jsonb_build_object('cron', coalesce((
    select jsonb_agg(jsonb_build_object('name', j.jobname, 'schedule', j.schedule, 'command', j.command) order by j.jobname)
    from cron.job j), '[]'::jsonb));

  -- extensions, realtime publication, storage buckets
  out := out || jsonb_build_object('extensions', coalesce((
    select jsonb_agg(e.extname order by e.extname) from pg_extension e), '[]'::jsonb));
  out := out || jsonb_build_object('realtime', coalesce((
    select jsonb_agg(pt.schemaname || '.' || pt.tablename) from pg_publication_tables pt where pt.pubname = 'supabase_realtime'), '[]'::jsonb));
  out := out || jsonb_build_object('buckets', coalesce((
    select jsonb_agg(jsonb_build_object('id', b.id, 'public', b.public)) from storage.buckets b), '[]'::jsonb));

  return out;
end
$function$
;
revoke all on function public.admin_schema_snapshot() from public, anon, authenticated;
grant execute on function public.admin_schema_snapshot() to service_role;

CREATE OR REPLACE FUNCTION public.admin_stats()
 RETURNS json
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with admins as (select id from profiles where is_admin is true)
  select json_build_object(
    'players',  (select count(*) from profiles where is_admin is not true),
    'members',  (select count(*) from profiles where is_admin is not true and is_premium and (premium_expires_at is null or premium_expires_at > now())),
    'activePlayers', (select count(*) from profiles where is_admin is not true and last_seen_at > now() - interval '7 days'),
    'badgesEarned', coalesce((select sum(coalesce(array_length(unlocked_badges, 1), 0)) from profiles where is_admin is not true), 0),
    'flex', json_build_object(
      'fishCaught', coalesce((select sum(catch_count) from fish_collection where user_id not in (select id from admins)), 0),
      'distanceSailed', coalesce((select sum(tide_run_total_distance) from profiles where is_admin is not true), 0),
      'biggestFish', coalesce(
        (select json_build_object(
          'length', pb.best_length_in,
          'species', fs.name,
          'username', p.username
        )
        from fish_personal_bests pb
        join fish_species fs on fs.id = pb.fish_id
        join profiles p on p.id = pb.user_id
        where pb.user_id not in (select id from admins)
        order by pb.best_length_in desc nulls last
        limit 1),
        '{}'::json
      ),
      'longestPerfectStreak', coalesce((select max(highest_perfect_streak) from profiles where is_admin is not true), 0),
      'longestPerfectStreakBy', (
        select username from profiles
        where is_admin is not true and highest_perfect_streak > 0
        order by highest_perfect_streak desc nulls last
        limit 1
      ),
      'biggestTavernPayout', coalesce(
        (select json_build_object(
          'amount', at.payout,
          'game', at.game,
          'username', p.username
        )
        from (
          select 'Slots' as game, payout, user_id from slot_spins where user_id not in (select id from admins)
          union all
          select 'Crown & Anchor' as game, payout, user_id from dice_rolls where user_id not in (select id from admins)
          union all
          select 'Blackjack' as game, net_delta as payout, user_id from blackjack_hands where user_id not in (select id from admins)
        ) at
        left join profiles p on p.id = at.user_id
        order by at.payout desc nulls last
        limit 1),
        '{}'::json
      )
    ),
    'fishing', json_build_object(
      'casts',    coalesce((select sum(fishing_casts) from profiles where is_admin is not true), 0),
      'perfects', coalesce((select sum(total_perfects) from profiles where is_admin is not true), 0),
      'caught',   coalesce((select sum(catch_count) from fish_collection where user_id not in (select id from admins)), 0),
      'species',  (select count(distinct fish_id) from fish_collection where user_id not in (select id from admins)),
      'jackpots', coalesce((select sum(fishing_jackpots) from profiles where is_admin is not true), 0),
      'doubles',  coalesce((select sum(fishing_double_catches) from profiles where is_admin is not true), 0),
      'snags',    coalesce((select sum(fishing_snags) from profiles where is_admin is not true), 0),
      'crates',   coalesce((select sum(fishing_crates_opened) from profiles where is_admin is not true), 0),
      'personalBests', (select count(*) from fish_personal_bests where user_id not in (select id from admins))
    ),
    -- Prestige — zone resets. Captains = players with at least one
    -- prestiged zone; stars = total stars lit fleet-wide (capped 5/zone,
    -- matching the badge math on /achievements).
    'prestige', json_build_object(
      'captains', (
        select count(*) from profiles p
        where p.is_admin is not true and exists (
          select 1 from jsonb_each_text(coalesce(p.prestige_levels, '{}'::jsonb)) v
          where (v.value)::int >= 1
        )
      ),
      'stars', coalesce((
        select sum(least(5, (v.value)::int))
        from profiles p, jsonb_each_text(coalesce(p.prestige_levels, '{}'::jsonb)) v
        where p.is_admin is not true
      ), 0)
    ),
    -- Goldens (1/1000 Perfect catches, terminal-state Sell or Mount).
    -- Each row in shiny_catches is one landed golden; status reflects
    -- the player's forced choice at the result moment.
    'goldens', json_build_object(
      'total',   (select count(*) from shiny_catches where user_id not in (select id from admins)),
      'mounted', (select count(*) from shiny_catches where status = 'mounted' and user_id not in (select id from admins)),
      'sold',    (select count(*) from shiny_catches where status = 'sold' and user_id not in (select id from admins)),
      'topCaptainCount', coalesce((
        select max(c) from (
          select count(*) as c from shiny_catches
          where user_id not in (select id from admins)
          group by user_id
        ) t
      ), 0),
      'topCaptainBy', (
        select p.username
        from shiny_catches sc
        join profiles p on p.id = sc.user_id
        where sc.user_id not in (select id from admins)
        group by p.username
        order by count(*) desc
        limit 1
      )
    ),
    'raids', json_build_object(
      'cleared',      (select count(*) from raid_completions where user_id not in (select id from admins)),
      'biggestHit',   coalesce((select max(highest_raid_damage) from profiles where is_admin is not true), 0),
      'biggestHitBy', (select username from profiles where is_admin is not true order by highest_raid_damage desc nulls last limit 1),
      'byBoss', (
        select coalesce(
          json_agg(json_build_object('raidId', raid_id, 'players', players, 'completions', completions) order by players desc),
          '[]'::json
        )
        from (
          select raid_id, count(distinct user_id)::int as players, count(*)::int as completions
          from raid_completions
          where user_id not in (select id from admins)
          group by raid_id
        ) t
      )
    ),
    'tideRun', json_build_object(
      'distance',      coalesce((select sum(tide_run_total_distance) from profiles where is_admin is not true), 0),
      'beacons',       coalesce((select sum(tide_run_beacons_smashed) from profiles where is_admin is not true), 0),
      'longest',       coalesce((select max(tide_run_best_distance) from profiles where is_admin is not true), 0),
      'longestBy',     (select username from profiles where is_admin is not true order by tide_run_best_distance desc nulls last limit 1),
      'mostBeacons',   coalesce((select max(tide_run_beacons_smashed) from profiles where is_admin is not true), 0),
      'mostBeaconsBy', (select username from profiles where is_admin is not true order by tide_run_beacons_smashed desc nulls last limit 1)
    ),
    'voyages', json_build_object(
      'completed', (select count(*) from daily_voyages where status = 'revealed' and user_id not in (select id from admins)),
      'loot',      coalesce((select sum(total_doubloons) from daily_voyages where status = 'revealed' and user_id not in (select id from admins)), 0),
      'crewLost',  coalesce((select sum(coalesce(array_length(crew_lost, 1), 0)) from daily_voyages where status = 'revealed' and user_id not in (select id from admins)), 0)
    ),
    'recruits', json_build_object(
      'lifetime',  coalesce((select sum(lifetime_recruits) from profiles where is_admin is not true), 0),
      'total',     (select count(*) from user_crew where died_at is null and user_id not in (select id from admins)),
      'legendary', (select count(*) from user_crew where rarity = 4 and died_at is null and user_id not in (select id from admins)),
      'epic',      (select count(*) from user_crew where rarity = 3 and died_at is null and user_id not in (select id from admins)),
      'rare',      (select count(*) from user_crew where rarity = 2 and died_at is null and user_id not in (select id from admins)),
      'common',    (select count(*) from user_crew where rarity = 1 and died_at is null and user_id not in (select id from admins)),
      'deployed',  (select count(*) from user_crew where (voyage_slot is not null or raid_slot is not null) and died_at is null and user_id not in (select id from admins)),
      'fallen',    (select count(*) from user_crew where died_at is not null and user_id not in (select id from admins)),
      'nicknamed', (select count(*) from user_crew where nickname is not null and died_at is null and user_id not in (select id from admins)),
      'topXP',     coalesce((select max(xp) from user_crew where died_at is null and user_id not in (select id from admins)), 0),
      'topXPBy',   (
        select p.username from user_crew uc
        join profiles p on p.id = uc.user_id
        where uc.died_at is null and uc.user_id not in (select id from admins)
        order by uc.xp desc nulls last
        limit 1
      ),
      -- Crew Hall ladder (tiers 1-5, default 1). Upgrades bought =
      -- total rungs climbed fleet-wide; hallMaxed = captains at tier 5.
      'hallUpgrades', coalesce((select sum(greatest(coalesce(crew_hall_tier, 1) - 1, 0)) from profiles where is_admin is not true), 0),
      'hallMaxed',    (select count(*) from profiles where is_admin is not true and crew_hall_tier >= 5)
    ),
    -- Tavern minigames. Slots is the long-runner; Blackjack is the
    -- main wager game now. Crown & Anchor (dice_rolls) was retired
    -- but the historical totals stay surfaced for reference.
    'tavern', json_build_object(
      'slotSpins',  (select count(*) from slot_spins where user_id not in (select id from admins)),
      'slotWins',   (select count(*) from slot_spins where payout > 0 and user_id not in (select id from admins)),
      'slotBiggest', coalesce((select max(payout) from slot_spins where user_id not in (select id from admins)), 0)
    ),
    -- Catfish Jackpot — single-row state table; history is only the
    -- last claim, so that's what we surface alongside the live pot.
    'jackpot', json_build_object(
      'pot',        coalesce((select pot from slots_jackpot limit 1), 0),
      'lastAmount', coalesce((select last_win_amount from slots_jackpot limit 1), 0),
      'lastBy',     (select last_winner_name from slots_jackpot limit 1),
      'lastAt',     (select last_won_at from slots_jackpot limit 1)
    ),
    -- The Den — shared casino chip wallet across blackjack / roulette /
    -- slots. Chips in play = un-cashed-out balances; buy-ins are the
    -- doubloons converted in (5k/day cap lives on casino_buy_ins).
    'den', json_build_object(
      'chipsHeld',  coalesce((select sum(casino_chips) from profiles where is_admin is not true), 0),
      'buyIns',     (select count(*) from casino_buy_ins where user_id not in (select id from admins)),
      'buyInTotal', coalesce((select sum(amount) from casino_buy_ins where user_id not in (select id from admins)), 0)
    ),
    'blackjack', json_build_object(
      'hands',         (select count(*) from blackjack_hands where user_id not in (select id from admins)),
      'totalWagered',  coalesce((select sum(total_wagered) from blackjack_hands where user_id not in (select id from admins)), 0),
      'biggestWin',    coalesce((select max(net_delta) from blackjack_hands where user_id not in (select id from admins)), 0),
      'biggestWinBy',  (
        select p.username from blackjack_hands bj
        join profiles p on p.id = bj.user_id
        where bj.user_id not in (select id from admins)
        order by bj.net_delta desc nulls last
        limit 1
      ),
      'biggestLoss',   coalesce((select abs(min(net_delta)) from blackjack_hands where net_delta < 0 and user_id not in (select id from admins)), 0),
      'biggestLossBy', (
        select p.username from blackjack_hands bj
        join profiles p on p.id = bj.user_id
        where bj.net_delta < 0 and bj.user_id not in (select id from admins)
        order by bj.net_delta asc nulls last
        limit 1
      )
    ),
    'roulette', json_build_object(
      'spins',         (select count(*) from roulette_spins where user_id not in (select id from admins)),
      'totalWagered',  coalesce((select sum(total_wagered) from roulette_spins where user_id not in (select id from admins)), 0),
      'biggestWin',    coalesce((select max(net_chips) from roulette_spins where user_id not in (select id from admins)), 0)
    ),
    -- The Parlor — trivia hub. Board = Captain's Board daily category
    -- column; ladder = Pirate King weekly 10-rung climb (crowned /
    -- walked / busted are the three terminal states).
    'parlor', json_build_object(
      'boardPlays',   (select count(*) from trivia_board_attempts where user_id not in (select id from admins)),
      'boardPayout',  coalesce((select sum(coalesce(doubloons_awarded, 0)) from trivia_board_attempts where user_id not in (select id from admins)), 0),
      'ladderRuns',   (select count(*) from trivia_ladder_attempts where user_id not in (select id from admins)),
      'kingsCrowned', (select count(*) from trivia_ladder_attempts where status = 'crowned' and user_id not in (select id from admins)),
      'walked',       (select count(*) from trivia_ladder_attempts where status = 'walked' and user_id not in (select id from admins)),
      'busted',       (select count(*) from trivia_ladder_attempts where status = 'busted' and user_id not in (select id from admins)),
      'ladderPayout', coalesce((select sum(coalesce(doubloons_awarded, 0)) from trivia_ladder_attempts where user_id not in (select id from admins)), 0)
    ),
    'mail', json_build_object(
      'messages', (select count(*) from mail_messages),
      'reads',    (select count(*) from mail_reads where user_id not in (select id from admins)),
      'claims',   (select count(*) from mail_reads where claimed_at is not null and user_id not in (select id from admins))
    ),
    -- Daily Challenges. claimed_1/2/3 booleans on each row; total
    -- completions = sum of trues across all three picks.
    'dailyChallenges', json_build_object(
      'completed', coalesce((
        select sum( (claimed_1::int) + (claimed_2::int) + (claimed_3::int) )
        from daily_challenge_progress
        where user_id not in (select id from admins)
      ), 0),
      'activeDays', (select count(distinct (user_id, date)) from daily_challenge_progress where user_id not in (select id from admins))
    ),
    'economy', json_build_object(
      'fishSold',        coalesce((select sum(amount) from doubloon_transactions where (reason like 'Sold fish%' or reason = 'Pending sale settled') and user_id not in (select id from admins)), 0),
      'doubloonsEarned', coalesce((select sum(amount) from doubloon_transactions where amount > 0 and reason <> 'Admin grant' and user_id not in (select id from admins)), 0),
      'doubloonsSpent',  coalesce((select -sum(amount) from doubloon_transactions where amount < 0 and user_id not in (select id from admins)), 0),
      'gemsEarned',      coalesce((select sum(amount) from gem_transactions where amount > 0 and reason <> 'Admin grant' and user_id not in (select id from admins)), 0),
      'doubloonsHeld',   coalesce((select sum(doubloons) from profiles where is_admin is not true), 0),
      'gemsHeld',        coalesce((select sum(gems) from profiles where is_admin is not true), 0),
      -- Patient sells = the 90%-in-1h delayed liquidate lane; count of
      -- settled payouts (transactions, not in-flight pending_sales rows).
      'patientSells',    (select count(*) from doubloon_transactions where reason = 'Pending sale settled' and user_id not in (select id from admins))
    )
  );
$function$
;
revoke all on function public.admin_stats() from public, anon, authenticated;
grant execute on function public.admin_stats() to anon;
grant execute on function public.admin_stats() to authenticated;
grant execute on function public.admin_stats() to public;
grant execute on function public.admin_stats() to service_role;

CREATE OR REPLACE FUNCTION public.bump_fish_lifetime(uid uuid, fid integer, n integer, at timestamp with time zone)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into fish_lifetime (user_id, fish_id, catches, first_caught_at, last_caught_at)
  values (uid, fid, n, at, at)
  on conflict (user_id, fish_id) do update
    set catches        = fish_lifetime.catches + excluded.catches,
        first_caught_at = least(coalesce(fish_lifetime.first_caught_at, excluded.first_caught_at), excluded.first_caught_at),
        last_caught_at  = greatest(coalesce(fish_lifetime.last_caught_at, excluded.last_caught_at), excluded.last_caught_at);
end $function$
;
revoke all on function public.bump_fish_lifetime(uid uuid, fid integer, n integer, at timestamp with time zone) from public, anon, authenticated;
grant execute on function public.bump_fish_lifetime(uid uuid, fid integer, n integer, at timestamp with time zone) to service_role;

CREATE OR REPLACE FUNCTION public.bump_gauntlet_hit(uid uuid, dmg integer)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  update profiles
  set gauntlet_big_hit = greatest(coalesce(gauntlet_big_hit, 0), dmg),
      gauntlet_big_hit_at = case when dmg > coalesce(gauntlet_big_hit, 0) then now() else gauntlet_big_hit_at end
  where id = uid;
$function$
;
revoke all on function public.bump_gauntlet_hit(uid uuid, dmg integer) from public, anon, authenticated;
grant execute on function public.bump_gauntlet_hit(uid uuid, dmg integer) to anon;
grant execute on function public.bump_gauntlet_hit(uid uuid, dmg integer) to authenticated;
grant execute on function public.bump_gauntlet_hit(uid uuid, dmg integer) to public;
grant execute on function public.bump_gauntlet_hit(uid uuid, dmg integer) to service_role;

CREATE OR REPLACE FUNCTION public.bump_profile_json_counter(uid uuid, col text, key text, n integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if col not in ('crate_opens', 'bait_used') then
    raise exception 'bump_profile_json_counter: % is not a counter map', col;
  end if;
  if key is null or key = '' or length(key) > 40 then
    raise exception 'bump_profile_json_counter: bad key';
  end if;
  execute format(
    'update profiles set %I = jsonb_set(coalesce(%I, ''{}''::jsonb), array[$1], '
    || 'to_jsonb(coalesce((%I -> $1)::int, 0) + $2), true) where id = $3',
    col, col, col
  ) using key, n, uid;
end $function$
;
revoke all on function public.bump_profile_json_counter(uid uuid, col text, key text, n integer) from public, anon, authenticated;
grant execute on function public.bump_profile_json_counter(uid uuid, col text, key text, n integer) to service_role;

CREATE OR REPLACE FUNCTION public.bump_profile_max(uid uuid, col text, v integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if col not in ('biggest_fish_sale') then
    raise exception 'bump_profile_max: % is not a high-water column', col;
  end if;
  execute format('update profiles set %I = greatest(coalesce(%I, 0), $1) where id = $2', col, col)
    using v, uid;
end $function$
;
revoke all on function public.bump_profile_max(uid uuid, col text, v integer) from public, anon, authenticated;
grant execute on function public.bump_profile_max(uid uuid, col text, v integer) to service_role;

CREATE OR REPLACE FUNCTION public.bump_profile_stat(uid uuid, col text, n integer)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  execute format('update profiles set %I = coalesce(%I, 0) + $1 where id = $2', col, col) using n, uid;
end $function$
;
revoke all on function public.bump_profile_stat(uid uuid, col text, n integer) from public, anon, authenticated;
grant execute on function public.bump_profile_stat(uid uuid, col text, n integer) to service_role;

CREATE OR REPLACE FUNCTION public.bump_pvp_stats(uid uuid, wins integer, losses integer)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update public.profiles
     set pvp_wins   = coalesce(pvp_wins, 0)   + wins,
         pvp_losses = coalesce(pvp_losses, 0) + losses
   where id = uid;
$function$
;
revoke all on function public.bump_pvp_stats(uid uuid, wins integer, losses integer) from public, anon, authenticated;
grant execute on function public.bump_pvp_stats(uid uuid, wins integer, losses integer) to service_role;

CREATE OR REPLACE FUNCTION public.bump_raid_damage(uid uuid, dmg integer)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  update profiles set highest_raid_damage = greatest(coalesce(highest_raid_damage, 0), dmg) where id = uid;
$function$
;
revoke all on function public.bump_raid_damage(uid uuid, dmg integer) from public, anon, authenticated;
grant execute on function public.bump_raid_damage(uid uuid, dmg integer) to service_role;

CREATE OR REPLACE FUNCTION public.bump_run_token_kill(p_id uuid, p_uid uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update run_tokens set kills = kills + 1
  where id = p_id and user_id = p_uid and kind = 'raid'
    and consumed_at is null and expires_at > now()
    and kills < coalesce((meta->>'maxKills')::int, 999999)
  returning true;
$function$
;
revoke all on function public.bump_run_token_kill(p_id uuid, p_uid uuid) from public, anon, authenticated;
grant execute on function public.bump_run_token_kill(p_id uuid, p_uid uuid) to service_role;

CREATE OR REPLACE FUNCTION public.career_stats(uid uuid)
 RETURNS json
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select json_build_object(
    'fishSold', coalesce((select fish_sold_doubloons from profiles where id = uid), 0),
    'voyageLoot', coalesce((select sum(total_doubloons) from daily_voyages where user_id = uid and status = 'revealed'), 0),
    'raidsCompleted', (select count(*) from raid_completions where user_id = uid)
  );
$function$
;
revoke all on function public.career_stats(uid uuid) from public, anon, authenticated;
grant execute on function public.career_stats(uid uuid) to anon;
grant execute on function public.career_stats(uid uuid) to authenticated;
grant execute on function public.career_stats(uid uuid) to public;
grant execute on function public.career_stats(uid uuid) to service_role;

CREATE OR REPLACE FUNCTION public.casino_cash_out(uid uuid)
 RETURNS TABLE(paid integer, doubloons integer)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with before as (select casino_chips as c from public.profiles where id = uid for update)
  update public.profiles p
     set doubloons = p.doubloons + before.c, casino_chips = 0
    from before
   where p.id = uid and before.c > 0
  returning before.c, p.doubloons;
$function$
;
revoke all on function public.casino_cash_out(uid uuid) from public, anon, authenticated;
grant execute on function public.casino_cash_out(uid uuid) to service_role;

CREATE OR REPLACE FUNCTION public.check_rate_limit(p_key text, p_max integer, p_window_seconds integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_count INT;
  v_window_start TIMESTAMPTZ;
BEGIN
  SELECT count, window_start INTO v_count, v_window_start
  FROM rate_limits
  WHERE key = p_key
  FOR UPDATE;

  IF NOT FOUND OR NOW() > v_window_start + (p_window_seconds * INTERVAL '1 second') THEN
    INSERT INTO rate_limits (key, count, window_start)
    VALUES (p_key, 1, NOW())
    ON CONFLICT (key) DO UPDATE SET count = 1, window_start = NOW();
    RETURN TRUE;
  END IF;

  IF v_count >= p_max THEN
    RETURN FALSE;
  END IF;

  UPDATE rate_limits SET count = count + 1 WHERE key = p_key;
  RETURN TRUE;
END;
$function$
;
revoke all on function public.check_rate_limit(p_key text, p_max integer, p_window_seconds integer) from public, anon, authenticated;
grant execute on function public.check_rate_limit(p_key text, p_max integer, p_window_seconds integer) to service_role;

CREATE OR REPLACE FUNCTION public.claim_badge_reward(p_user uuid, p_badge text, p_amount integer, p_gems integer DEFAULT 0)
 RETURNS TABLE(new_doubloons bigint, new_gems bigint, claimed text[], granted boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  did_grant boolean := false;
begin
  update public.profiles
     set doubloons = doubloons + p_amount,
         gems = gems + p_gems,
         claimed_badge_rewards = array_append(claimed_badge_rewards, p_badge)
   where id = p_user
     and p_badge = any(coalesce(unlocked_badges, '{}'))
     and not (p_badge = any(coalesce(claimed_badge_rewards, '{}')));
  if found then did_grant := true; end if;

  return query
    select p.doubloons::bigint, p.gems::bigint, p.claimed_badge_rewards, did_grant
      from public.profiles p
     where p.id = p_user;
end;
$function$
;
revoke all on function public.claim_badge_reward(p_user uuid, p_badge text, p_amount integer, p_gems integer) from public, anon, authenticated;
grant execute on function public.claim_badge_reward(p_user uuid, p_badge text, p_amount integer, p_gems integer) to service_role;

CREATE OR REPLACE FUNCTION public.claim_bounty_slot(uid uuid, slot integer, today text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ok boolean;
begin
  update bounty_progress
     set claimed = claimed[1:slot] || array[true] || claimed[slot + 2:],
         updated_at = now()
   where user_id = uid
     and date = today
     and coalesce(claimed[slot + 1], false) = false
  returning true into ok;

  return coalesce(ok, false);
end
$function$
;
revoke all on function public.claim_bounty_slot(uid uuid, slot integer, today text) from public, anon, authenticated;
grant execute on function public.claim_bounty_slot(uid uuid, slot integer, today text) to service_role;

CREATE OR REPLACE FUNCTION public.claim_mail(uid uuid, mid uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  msg RECORD;
  v_joined timestamptz;
  rows_affected int;
BEGIN
  SELECT id, attachment_gems, attachment_doubloons, target_user_id, evergreen, created_at
    INTO msg FROM mail_messages WHERE id = mid;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'not_found');
  END IF;

  -- Visibility guard (mirrors getInbox). Targeted mail is claimable only by its
  -- recipient; a non-evergreen broadcast only by players who joined on/before it
  -- was sent. Blocks claiming a hidden mail's reward via a crafted id.
  IF msg.target_user_id IS NOT NULL AND msg.target_user_id <> uid THEN
    RETURN jsonb_build_object('error', 'not_found');
  END IF;
  IF msg.target_user_id IS NULL AND NOT msg.evergreen THEN
    SELECT created_at INTO v_joined FROM auth.users WHERE id = uid;
    IF v_joined IS NULL OR msg.created_at < v_joined THEN
      RETURN jsonb_build_object('error', 'not_found');
    END IF;
  END IF;

  IF msg.attachment_gems = 0 AND msg.attachment_doubloons = 0 THEN
    RETURN jsonb_build_object('error', 'no_attachment');
  END IF;

  INSERT INTO mail_reads (user_id, message_id, read_at, claimed_at)
  VALUES (uid, mid, now(), now())
  ON CONFLICT (user_id, message_id) DO UPDATE
    SET claimed_at = EXCLUDED.claimed_at
    WHERE mail_reads.claimed_at IS NULL;

  GET DIAGNOSTICS rows_affected = ROW_COUNT;
  IF rows_affected = 0 THEN
    RETURN jsonb_build_object('error', 'already_claimed');
  END IF;

  UPDATE profiles
    SET gems = COALESCE(gems, 0) + msg.attachment_gems,
        doubloons = COALESCE(doubloons, 0) + msg.attachment_doubloons
    WHERE id = uid;

  RETURN jsonb_build_object(
    'ok', true,
    'gems', msg.attachment_gems,
    'doubloons', msg.attachment_doubloons
  );
END;
$function$
;
revoke all on function public.claim_mail(uid uuid, mid uuid) from public, anon, authenticated;
grant execute on function public.claim_mail(uid uuid, mid uuid) to service_role;

CREATE OR REPLACE FUNCTION public.claim_run_token_round(p_id uuid, p_uid uuid, p_round integer)
 RETURNS jsonb
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update run_tokens
     set paid_rounds = array_append(paid_rounds, p_round),
         kills = kills + 1
   where id = p_id and user_id = p_uid and kind = 'raid'
     and consumed_at is null and expires_at > now()
     and p_round >= 0
     and not (p_round = any(paid_rounds))
  returning meta;
$function$
;
revoke all on function public.claim_run_token_round(p_id uuid, p_uid uuid, p_round integer) from public, anon, authenticated;
grant execute on function public.claim_run_token_round(p_id uuid, p_uid uuid, p_round integer) to service_role;

CREATE OR REPLACE FUNCTION public.claim_token(p_token text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_row   claim_tokens%rowtype;
  v_uid   uuid;
  v_email text;
  v_gems  integer;
begin
  v_uid := auth.uid();
  if v_uid is null then
    return jsonb_build_object('status', 'not_authenticated');
  end if;

  select email into v_email from auth.users where id = v_uid;
  select * into v_row from claim_tokens where token = p_token;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_row.status != 'pending' then
    return jsonb_build_object('status', 'already_claimed');
  end if;
  if v_row.expires_at is not null and v_row.expires_at < now() then
    return jsonb_build_object('status', 'expired');
  end if;
  if v_row.email is not null and lower(v_row.email) != lower(v_email) then
    return jsonb_build_object('status', 'email_mismatch');
  end if;

  -- THE CLAIM IS THE GUARD: two claims fired together both saw 'pending'
  -- above; only one of them flips it here.
  update claim_tokens
     set status = 'claimed', claimed_by = v_uid, claimed_at = now()
   where token = p_token and status = 'pending';
  if not found then
    return jsonb_build_object('status', 'already_claimed');
  end if;

  v_gems := v_row.packs_to_grant * 100;
  insert into profiles (id, gems)
    values (v_uid, v_gems)
    on conflict (id) do update
      set gems = profiles.gems + excluded.gems;

  return jsonb_build_object('status', 'ok', 'gems', v_gems, 'packs', v_row.packs_to_grant);
end;
$function$
;
revoke all on function public.claim_token(p_token text) from public, anon, authenticated;
grant execute on function public.claim_token(p_token text) to authenticated;
grant execute on function public.claim_token(p_token text) to service_role;

CREATE OR REPLACE FUNCTION public.deduct_doubloons(uid uuid, amount integer)
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  UPDATE public.profiles
     SET doubloons = doubloons - amount
   WHERE id = uid AND amount >= 0 AND doubloons >= amount
  RETURNING doubloons;
$function$
;
revoke all on function public.deduct_doubloons(uid uuid, amount integer) from public, anon, authenticated;
grant execute on function public.deduct_doubloons(uid uuid, amount integer) to service_role;

CREATE OR REPLACE FUNCTION public.exchange_live_value(p_stake numeric, p_leverage numeric, p_move numeric, p_remaining numeric, p_term numeric)
 RETURNS integer
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
declare
  INV_SQRT_2PI constant double precision := 0.3989422804014327;
  HOUSE_EDGE   constant double precision := 0.08;
  v_s   double precision;
  v_z   double precision;
  v_t   double precision;
  v_p   double precision;
  v_pdf double precision;
  v_cdf double precision;
  v_exp double precision;
begin
  if p_leverage is null or p_leverage <= 0 then return 0; end if;
  -- At or past expiry it is worth its intrinsic value and nothing more, which
  -- is the same thing settle_exchange_contracts pays.
  if p_remaining is null or p_remaining <= 0 or p_term is null or p_term <= 0 then
    return greatest(0, round(p_stake * p_leverage * greatest(0, p_move)))::int;
  end if;

  v_s := ((1 - HOUSE_EDGE) / (INV_SQRT_2PI * p_leverage)) * sqrt(p_remaining::double precision / p_term::double precision);
  if not (v_s > 0) then
    return greatest(0, round(p_stake * p_leverage * greatest(0, p_move)))::int;
  end if;

  v_z   := p_move::double precision / v_s;
  v_pdf := INV_SQRT_2PI * exp(-0.5 * v_z * v_z);
  v_t   := 1 / (1 + 0.2316419 * abs(v_z));
  v_p   := v_pdf * v_t * (0.319381530 + v_t * (-0.356563782 + v_t * (1.781477937 + v_t * (-1.821255978 + v_t * 1.330274429))));
  v_cdf := case when v_z >= 0 then 1 - v_p else v_p end;
  v_exp := p_move::double precision * v_cdf + v_s * v_pdf;

  return greatest(0, round((p_stake * p_leverage)::double precision * v_exp))::int;
end $function$
;
revoke all on function public.exchange_live_value(p_stake numeric, p_leverage numeric, p_move numeric, p_remaining numeric, p_term numeric) from public, anon, authenticated;
grant execute on function public.exchange_live_value(p_stake numeric, p_leverage numeric, p_move numeric, p_remaining numeric, p_term numeric) to service_role;

CREATE OR REPLACE FUNCTION public.get_badge_rarity()
 RETURNS TABLE(badge_id text, pct real)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH players AS (
    SELECT unlocked_badges
    FROM profiles
    WHERE NOT COALESCE(is_admin, false)
      AND (COALESCE(fishing_xp, 0) > 0 OR COALESCE(expedition_xp, 0) > 0)
  ),
  total AS (SELECT GREATEST(count(*), 1)::real AS n FROM players)
  SELECT b AS badge_id,
         (count(*)::real / (SELECT n FROM total) * 100.0)::real AS pct
  FROM players p, unnest(p.unlocked_badges) AS b
  GROUP BY b;
$function$
;
revoke all on function public.get_badge_rarity() from public, anon, authenticated;
grant execute on function public.get_badge_rarity() to service_role;

CREATE OR REPLACE FUNCTION public.get_slot_stats(uid uuid)
 RETURNS TABLE(spins bigint, net bigint, biggest_win bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select
    count(*)::bigint,
    coalesce(sum(payout - wager), 0)::bigint,
    coalesce(max(payout - wager), 0)::bigint
  from public.slot_spins
  where user_id = uid
$function$
;
revoke all on function public.get_slot_stats(uid uuid) from public, anon, authenticated;
grant execute on function public.get_slot_stats(uid uuid) to public;
grant execute on function public.get_slot_stats(uid uuid) to service_role;

CREATE OR REPLACE FUNCTION public.get_user_by_email(p_email text)
 RETURNS uuid
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id from auth.users where lower(email) = lower(p_email) limit 1;
$function$
;
revoke all on function public.get_user_by_email(p_email text) from public, anon, authenticated;
grant execute on function public.get_user_by_email(p_email text) to service_role;

CREATE OR REPLACE FUNCTION public.grant_crew_xp_pairs(uid uuid, pairs jsonb)
 RETURNS TABLE(id bigint, old_xp integer, new_xp integer)
 LANGUAGE sql
 SET search_path TO 'public', 'pg_temp'
AS $function$
  update public.user_crew uc
  set xp = uc.xp + p.grant_xp
  from (
    select (e->>'id')::bigint as crew_id,
           (e->>'xp')::int    as grant_xp
    from jsonb_array_elements(pairs) e
  ) p
  where uc.user_id  = uid
    and uc.died_at is null
    and uc.id       = p.crew_id
    and p.grant_xp  > 0
  returning uc.id::bigint, (uc.xp - p.grant_xp)::int as old_xp, uc.xp::int as new_xp
$function$
;
revoke all on function public.grant_crew_xp_pairs(uid uuid, pairs jsonb) from public, anon, authenticated;
grant execute on function public.grant_crew_xp_pairs(uid uuid, pairs jsonb) to service_role;

CREATE OR REPLACE FUNCTION public.grant_crew_xp_to_assigned(uid uuid, grant_xp integer)
 RETURNS TABLE(id bigint, old_xp integer, new_xp integer)
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  UPDATE public.user_crew
  SET xp = xp + grant_xp
  WHERE user_id = uid AND died_at IS NULL AND raid_slot IS NOT NULL
  RETURNING user_crew.id::bigint, (user_crew.xp - grant_xp)::int AS old_xp, user_crew.xp::int AS new_xp
$function$
;
revoke all on function public.grant_crew_xp_to_assigned(uid uuid, grant_xp integer) from public, anon, authenticated;
grant execute on function public.grant_crew_xp_to_assigned(uid uuid, grant_xp integer) to service_role;

CREATE OR REPLACE FUNCTION public.grant_crew_xp_to_ids(uid uuid, crew_ids bigint[], grant_xp integer)
 RETURNS TABLE(id bigint, old_xp integer, new_xp integer)
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  UPDATE public.user_crew
  SET xp = xp + grant_xp
  WHERE user_id = uid AND died_at IS NULL AND id = ANY(crew_ids)
  RETURNING user_crew.id::bigint, (user_crew.xp - grant_xp)::int AS old_xp, user_crew.xp::int AS new_xp
$function$
;
revoke all on function public.grant_crew_xp_to_ids(uid uuid, crew_ids bigint[], grant_xp integer) from public, anon, authenticated;
grant execute on function public.grant_crew_xp_to_ids(uid uuid, crew_ids bigint[], grant_xp integer) to service_role;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;

  insert into public.bait_inventory (user_id, bait_type, quantity)
  values (new.id, 'worm', 25)
  on conflict (user_id, bait_type) do nothing;

  return new;
end;
$function$
;
revoke all on function public.handle_new_user() from public, anon, authenticated;
grant execute on function public.handle_new_user() to service_role;

CREATE OR REPLACE FUNCTION public.increment_doubloons(user_id uuid, amount integer)
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update profiles
     set doubloons = doubloons + amount
   where id = user_id
  returning doubloons;
$function$
;
revoke all on function public.increment_doubloons(user_id uuid, amount integer) from public, anon, authenticated;
grant execute on function public.increment_doubloons(user_id uuid, amount integer) to service_role;

CREATE OR REPLACE FUNCTION public.increment_gems(user_id uuid, amount integer)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update profiles
  set gems = gems + amount
  where id = user_id;
$function$
;
revoke all on function public.increment_gems(user_id uuid, amount integer) from public, anon, authenticated;
grant execute on function public.increment_gems(user_id uuid, amount integer) to service_role;

CREATE OR REPLACE FUNCTION public.profile_array_add(uid uuid, col text, val text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare n int; t text;
begin
  select data_type into t from information_schema.columns
   where table_schema = 'public' and table_name = 'profiles' and column_name = col;
  if t = 'ARRAY' then
    execute format(
      'update public.profiles set %1$I = array_append(coalesce(%1$I, ''{}''), $2)
        where id = $1 and not ($2 = any(coalesce(%1$I, ''{}'')))', col)
      using uid, val;
  elsif t = 'jsonb' then
    execute format(
      'update public.profiles set %1$I = coalesce(%1$I, ''[]''::jsonb) || to_jsonb($2)
        where id = $1 and jsonb_typeof(coalesce(%1$I, ''[]''::jsonb)) = ''array''
          and not (coalesce(%1$I, ''[]''::jsonb) ? $2)', col)
      using uid, val;
  else
    raise exception 'profile_array_add: column % not allowed', col;
  end if;
  get diagnostics n = row_count;
  return n > 0;
end $function$
;
revoke all on function public.profile_array_add(uid uuid, col text, val text) from public, anon, authenticated;
grant execute on function public.profile_array_add(uid uuid, col text, val text) to service_role;

CREATE OR REPLACE FUNCTION public.raid_progress_board()
 RETURNS TABLE(user_id uuid, username text, score integer, last_at timestamp with time zone)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT s.user_id, s.username, s.score, s.last_at FROM (
    SELECT p.id AS user_id, p.username,
      (CASE WHEN jsonb_typeof((p.raid_node_progress)::jsonb -> 'cleared') = 'array'
            THEN jsonb_array_length((p.raid_node_progress)::jsonb -> 'cleared') ELSE 0 END
       + coalesce(rc.boss_count, 0)
       + CASE WHEN p.has_completed_practice_raid THEN 1 ELSE 0 END)::int AS score,
      rc.last_at
    FROM profiles p
    LEFT JOIN (
      SELECT user_id, count(DISTINCT raid_id)::int AS boss_count, max(completed_at) AS last_at
      FROM raid_completions GROUP BY user_id
    ) rc ON rc.user_id = p.id
    WHERE p.is_admin = false
  ) s
  WHERE s.score > 0
  ORDER BY s.score DESC, s.last_at ASC NULLS LAST;
$function$
;
revoke all on function public.raid_progress_board() from public, anon, authenticated;
grant execute on function public.raid_progress_board() to public;
grant execute on function public.raid_progress_board() to service_role;

CREATE OR REPLACE FUNCTION public.raid_records(uid uuid)
 RETURNS TABLE(raid_id text, fastest_username text, fastest_ms integer, total_clearers integer, your_best_ms integer)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  WITH nonadmin AS (
    SELECT rc.raid_id, rc.user_id, rc.elapsed_ms, p.username
    FROM raid_completions rc
    JOIN profiles p ON p.id = rc.user_id
    WHERE coalesce(p.is_admin, false) = false
  ),
  fastest AS (
    SELECT DISTINCT ON (raid_id) raid_id, username AS fastest_username, elapsed_ms AS fastest_ms
    FROM nonadmin
    ORDER BY raid_id, elapsed_ms ASC NULLS LAST
  ),
  clearers AS (
    SELECT raid_id, count(DISTINCT user_id)::int AS total_clearers FROM nonadmin GROUP BY raid_id
  ),
  mine AS (
    SELECT raid_id, min(elapsed_ms)::int AS your_best_ms
    FROM raid_completions WHERE user_id = uid GROUP BY raid_id
  ),
  raids AS (
    SELECT raid_id FROM nonadmin UNION SELECT raid_id FROM mine
  )
  SELECT r.raid_id, f.fastest_username, f.fastest_ms::int,
         coalesce(c.total_clearers, 0)::int, m.your_best_ms
  FROM raids r
  LEFT JOIN fastest f ON f.raid_id = r.raid_id
  LEFT JOIN clearers c ON c.raid_id = r.raid_id
  LEFT JOIN mine m ON m.raid_id = r.raid_id;
$function$
;
revoke all on function public.raid_records(uid uuid) from public, anon, authenticated;
grant execute on function public.raid_records(uid uuid) to public;
grant execute on function public.raid_records(uid uuid) to service_role;

CREATE OR REPLACE FUNCTION public.record_gauntlet_depth_best(uid uuid, v text, hc boolean, d integer, ms integer)
 RETURNS TABLE(prev_ms integer, is_record boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare old_ms int;
begin
  if d < 1 or d > 100 or ms < 0 then
    return query select null::int, false;
    return;
  end if;

  select b.best_ms into old_ms
    from public.gauntlet_depth_bests b
   where b.user_id = uid and b.variant = v and b.hardcore = hc and b.depth = d;

  if old_ms is null then
    insert into public.gauntlet_depth_bests (user_id, variant, hardcore, depth, best_ms)
    values (uid, v, hc, d, ms)
    on conflict (user_id, variant, hardcore, depth) do nothing;
    -- First time this deep is not a "new best" -- there is nothing to have beaten,
    -- and the descent itself is already the moment. Caller tells them apart by
    -- prev_ms being null.
    return query select null::int, false;

  elsif ms < old_ms then
    update public.gauntlet_depth_bests b
       set best_ms = ms, achieved_at = now()
     where b.user_id = uid and b.variant = v and b.hardcore = hc and b.depth = d;
    return query select old_ms, true;

  else
    return query select old_ms, false;
  end if;
end $function$
;
revoke all on function public.record_gauntlet_depth_best(uid uuid, v text, hc boolean, d integer, ms integer) from public, anon, authenticated;
grant execute on function public.record_gauntlet_depth_best(uid uuid, v text, hc boolean, d integer, ms integer) to service_role;

CREATE OR REPLACE FUNCTION public.refresh_casino_leaderboards()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.leaderboard_blackjack;
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.leaderboard_fish_slots;
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.leaderboard_roulette;
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.leaderboard_den;
END $function$
;
revoke all on function public.refresh_casino_leaderboards() from public, anon, authenticated;
grant execute on function public.refresh_casino_leaderboards() to anon;
grant execute on function public.refresh_casino_leaderboards() to authenticated;
grant execute on function public.refresh_casino_leaderboards() to public;
grant execute on function public.refresh_casino_leaderboards() to service_role;

CREATE OR REPLACE FUNCTION public.set_default_username()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.username IS NULL THEN
    NEW.username := 'crew_' || LEFT(REPLACE(NEW.id::TEXT, '-', ''), 5);
  END IF;
  RETURN NEW;
END;
$function$
;
revoke all on function public.set_default_username() from public, anon, authenticated;
grant execute on function public.set_default_username() to anon;
grant execute on function public.set_default_username() to authenticated;
grant execute on function public.set_default_username() to public;
grant execute on function public.set_default_username() to service_role;

CREATE OR REPLACE FUNCTION public.settle_exchange_bets()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  b        record;
  v_exit   numeric;
  v_intr   numeric;
  v_payout bigint;
  v_count  integer := 0;
begin
  for b in
    select id from exchange_bets
     where status = 'open' and expires_at <= now()
     order by id limit 5000
  loop
    update exchange_bets set status = 'lost', settled_at = now()
     where id = b.id and status = 'open';
    if not found then continue; end if;

    declare bet exchange_bets%rowtype;
    begin
      select * into bet from exchange_bets where id = b.id;
      select price into v_exit from exchange_indexes where id = bet.index_id;
      if v_exit is null then v_exit := bet.entry_price; end if;

      -- Vanilla payoff, times the units ONE contract covers. A contract on a
      -- cheap index covers hundreds of them, the way a real option is written
      -- on a hundred shares.
      v_intr := case when bet.direction = 'up'
                     then v_exit - bet.strike
                     else bet.strike - v_exit end;
      v_payout := greatest(0, floor(bet.units * coalesce(bet.lot, 1) * greatest(v_intr, 0)))::bigint;

      update exchange_bets
         set status = case when v_payout > bet.stake then 'won' else 'lost' end,
             exit_price = v_exit, payout = v_payout
       where id = bet.id;

      if v_payout > 0 then
        update profiles set doubloons = doubloons + v_payout where id = bet.user_id;
        insert into doubloon_transactions (user_id, amount, reason)
        values (bet.user_id, v_payout, 'Exchange contract settled');
      end if;
      v_count := v_count + 1;
    end;
  end loop;
  return v_count;
end
$function$
;
revoke all on function public.settle_exchange_bets() from public, anon, authenticated;
grant execute on function public.settle_exchange_bets() to service_role;

CREATE OR REPLACE FUNCTION public.slots_claim_jackpot(p_user_id uuid, p_winner_name text, p_wager integer, p_max_bet integer)
 RETURNS TABLE(share integer, new_pot integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_share int;
  v_new int;
begin
  if p_max_bet is null or p_max_bet <= 0 then
    raise exception 'invalid max bet';
  end if;

  update public.slots_jackpot
  set last_win_amount = floor(pot * least(greatest(coalesce(p_wager, 0), 0), p_max_bet)::numeric / p_max_bet)::int,
      pot = greatest(seed, pot - floor(pot * least(greatest(coalesce(p_wager, 0), 0), p_max_bet)::numeric / p_max_bet)::int),
      last_winner_id = p_user_id,
      last_winner_name = p_winner_name,
      last_won_at = now(),
      updated_at = now()
  where id = 1
  returning last_win_amount, pot into v_share, v_new;

  return query select v_share, v_new;
end;
$function$
;
revoke all on function public.slots_claim_jackpot(p_user_id uuid, p_winner_name text, p_wager integer, p_max_bet integer) from public, anon, authenticated;
grant execute on function public.slots_claim_jackpot(p_user_id uuid, p_winner_name text, p_wager integer, p_max_bet integer) to service_role;

CREATE OR REPLACE FUNCTION public.slots_feed_jackpot(p_amount integer)
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  update public.slots_jackpot
  set pot = pot + greatest(coalesce(p_amount, 0), 0),
      updated_at = now()
  where id = 1
  returning pot;
$function$
;
revoke all on function public.slots_feed_jackpot(p_amount integer) from public, anon, authenticated;
grant execute on function public.slots_feed_jackpot(p_amount integer) to service_role;

CREATE OR REPLACE FUNCTION public.trawl_admin_stats()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select jsonb_build_object(
    'activeNow',        (select count(*) from public.trawls),
    'readyToCollect',   (select count(*) from public.trawls where ends_at <= now()),
    'captainsTrawling', (select count(distinct user_id) from public.trawls),
    'activeByZone', (
      select coalesce(jsonb_agg(jsonb_build_object('zone', zone, 'count', c) order by c desc), '[]'::jsonb)
      from (select zone, count(*) c from public.trawls group by zone) z
    ),
    'collections',     (select count(*) from public.doubloon_transactions where reason like 'Crew trawl:%'),
    'totalDoubloons',  (select coalesce(sum(amount), 0) from public.doubloon_transactions where reason like 'Crew trawl:%'),
    'avgDoubloons',    (select coalesce(round(avg(amount)), 0) from public.doubloon_transactions where reason like 'Crew trawl:%'),
    'uniqueCaptains',  (select count(distinct user_id) from public.doubloon_transactions where reason like 'Crew trawl:%'),
    'collections24h',  (select count(*) from public.doubloon_transactions where reason like 'Crew trawl:%' and created_at >= now() - interval '24 hours'),
    'doubloons24h',    (select coalesce(sum(amount), 0) from public.doubloon_transactions where reason like 'Crew trawl:%' and created_at >= now() - interval '24 hours'),
    'collections7d',   (select count(*) from public.doubloon_transactions where reason like 'Crew trawl:%' and created_at >= now() - interval '7 days'),
    'doubloons7d',     (select coalesce(sum(amount), 0) from public.doubloon_transactions where reason like 'Crew trawl:%' and created_at >= now() - interval '7 days'),
    'byZone', (
      select coalesce(jsonb_agg(jsonb_build_object('label', label, 'collections', c, 'doubloons', d) order by d desc), '[]'::jsonb)
      from (
        select substring(reason from 'Crew trawl: (.*)') as label, count(*) c, sum(amount) d
        from public.doubloon_transactions where reason like 'Crew trawl:%' group by reason
      ) z
    )
  );
$function$
;
revoke all on function public.trawl_admin_stats() from public, anon, authenticated;
grant execute on function public.trawl_admin_stats() to service_role;

CREATE OR REPLACE FUNCTION public.update_exchange_indexes()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  TREND_MAX  constant double precision := 0.0018;
  MAX_BIAS   constant double precision := 0.0125;
  DRIFT_K    constant double precision := 0.05;
  JUMP_P     constant double precision := 0.002;
  EVENT_MIN_DAYS constant double precision := 3;
  EVENT_MAX_DAYS constant double precision := 9;
  -- One gap in twenty goes far past the band. Lockstep with EXTREME_* in
  -- lib/exchangeBoard.ts. Capped: a price cannot fall further than all of it.
  EXTREME_P   constant double precision := 0.05;
  EXTREME_MIN constant double precision := 2;
  EXTREME_MAX constant double precision := 5;
  EXTREME_CAP constant double precision := 0.85;
  v_mood text; v_bias double precision; v_moodv double precision; r record;
  v_lp double precision; v_vol double precision; v_beta double precision;
  v_noise double precision; v_trend double precision; v_drift double precision;
  v_price double precision; v_ticks int; v_hist jsonb;
  v_jump double precision; v_note text; v_due boolean; v_next timestamptz;
  v_daily double precision; v_jmin double precision; v_jmax double precision;
  v_up   constant text[] := array[
    'a record haul reported', 'the shoals came back early', 'a rival fleet ran aground',
    'word of a bumper season', 'the nets came up heavy'];
  v_down constant text[] := array[
    'the beds came up empty', 'a spill fouled the grounds', 'the season closed early',
    'word of a die-off', 'the fleet found nothing'];
  v_flat constant text[] := array[
    'the count came in as expected', 'no change on the grounds', 'a quiet season, all told',
    'the books balanced, nothing more'];
  v_boom constant text[] := array[
    'a buyer took the whole fleet', 'the mother lode, and nobody saw it coming',
    'a new ground opened, and it is enormous'];
  v_bust constant text[] := array[
    'the grounds are fished out', 'the whole season written off',
    'the books were a lie, and the beds are bare'];
begin
  select mood, coalesce(mood_bias, 0)::double precision into v_mood, v_bias
    from market_state where id = 1;
  v_bias := coalesce(v_bias, 0) * 0.5;
  v_moodv := case v_mood when 'storm' then 1.5 when 'kraken' then 2.0
    when 'bounty_season' then 1.2 when 'cursed_waters' then 1.2 else 1.0 end;

  for r in select * from exchange_indexes loop
    v_vol := coalesce(r.vol, 0.05)::double precision;
    v_beta := coalesce(r.beta, 1.0)::double precision;
    v_price := coalesce(r.price, 1.0)::double precision;
    if not (v_price > 0) then v_price := 1.0; end if;
    v_lp := ln(v_price);
    v_trend := coalesce(r.trend, 0)::double precision;
    v_ticks := coalesce(r.trend_ticks, 0);
    v_next := r.next_event_at;

    if v_ticks <= 0 then
      v_trend := TREND_MAX * (0.35 + random() * 0.65)
                 * case when random() < 0.5 then 1 else -1 end;
      v_ticks := 72 + floor(random() * 264)::int;
    end if;

    v_drift := v_vol * DRIFT_K * (v_beta * (v_bias / MAX_BIAS) + v_trend / TREND_MAX);
    v_noise := (random() + random() + random() - 1.5) * v_vol * v_moodv;
    v_lp := v_lp + v_drift + v_noise;

    v_daily := v_vol * 2.449 * 100;
    v_jmin := greatest(3, least(15, 2 * v_daily)) / 100;
    v_jmax := greatest(8, least(40, 5 * v_daily)) / 100;
    if v_jmax <= v_jmin then v_jmax := v_jmin + 0.01; end if;

    v_due := v_next is not null and v_next <= now();
    v_jump := 0;
    if v_due then
      v_jump := random() * v_jmax;                          -- a report may say nothing
    elsif random() < JUMP_P then
      v_jump := v_jmin + random() * (v_jmax - v_jmin);      -- a surprise is news by definition
    end if;

    if v_jump <> 0 then
      -- THE TAIL. Rare, and it can take a price most of the way to nothing.
      if random() < EXTREME_P then
        v_jump := least(v_jump * (EXTREME_MIN + random() * (EXTREME_MAX - EXTREME_MIN)), EXTREME_CAP);
      end if;
      if random() < 0.5 then v_jump := -v_jump; end if;
      v_lp := v_lp + ln(1 + v_jump);

      if abs(v_jump) >= v_jmax * EXTREME_MIN then
        v_note := case when v_jump > 0
          then v_boom[1 + floor(random() * array_length(v_boom, 1))::int]
          else v_bust[1 + floor(random() * array_length(v_bust, 1))::int] end;
      elsif abs(v_jump) * 100 < greatest(0.4, v_daily * 0.5) then
        v_note := v_flat[1 + floor(random() * array_length(v_flat, 1))::int];
      elsif v_jump > 0 then
        v_note := v_up[1 + floor(random() * array_length(v_up, 1))::int];
      else
        v_note := v_down[1 + floor(random() * array_length(v_down, 1))::int];
      end if;
    end if;

    if v_due then
      v_next := now() + ((EVENT_MIN_DAYS + random() * (EVENT_MAX_DAYS - EVENT_MIN_DAYS))
                         || ' days')::interval;
    end if;

    v_price := exp(v_lp);
    if v_price is null or v_price <> v_price or v_price < 1e-12 or v_price > 1e15 then
      v_price := greatest(1e-12::double precision, least(1e15::double precision,
                   coalesce(nullif(v_price, 'NaN'::double precision), 1.0)));
    end if;

    v_hist := coalesce(r.history, '[]'::jsonb) || to_jsonb(round(coalesce(r.price, 1.0), 8));
    if jsonb_array_length(v_hist) > 48 then
      v_hist := (select jsonb_agg(elem order by ord) from (
        select elem, ord from jsonb_array_elements(v_hist) with ordinality as t(elem, ord)
        order by ord desc limit 48) sub);
    end if;

    update exchange_indexes set
      prev_price = price, price = round(v_price::numeric, 8),
      trend = v_trend, trend_ticks = v_ticks - 1,
      history = v_hist, updated_at = now(), next_event_at = v_next,
      last_event_at  = case when v_jump <> 0 then now() else last_event_at end,
      last_event     = case when v_jump <> 0 then v_note else last_event end,
      last_event_pct = case when v_jump <> 0 then round((v_jump * 100)::numeric, 1) else last_event_pct end
    where id = r.id;
  end loop;
end
$function$
;
revoke all on function public.update_exchange_indexes() from public, anon, authenticated;
grant execute on function public.update_exchange_indexes() to service_role;

CREATE OR REPLACE FUNCTION public.update_fish_market()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_mood text;
  v_mood_bias numeric;
  v_mood_expires_at timestamptz;
  v_roll float;
  r RECORD;
  v_volatility float;
  v_drift float;
  v_noise float;
  v_new_mult float;
  v_history jsonb;
BEGIN
  SELECT mood, mood_bias, mood_expires_at
    INTO v_mood, v_mood_bias, v_mood_expires_at
    FROM market_state WHERE id = 1;

  IF v_mood_expires_at IS NULL OR now() >= v_mood_expires_at THEN
    v_roll := random();
    IF v_roll < 0.05 THEN
      -- Kraken: extreme volatility, bidirectional
      v_mood := 'kraken';
      v_mood_bias := CASE WHEN random() < 0.5 THEN 0.02 ELSE -0.02 END;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    ELSIF v_roll < 0.10 THEN
      -- Bounty Season: strong bull
      v_mood := 'bounty_season';
      v_mood_bias := 0.025;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    ELSIF v_roll < 0.16 THEN
      -- Cursed Waters: strong bear
      v_mood := 'cursed_waters';
      v_mood_bias := -0.025;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    ELSIF v_roll < 0.28 THEN
      -- Tide Rising: weak bull
      v_mood := 'tide_rising';
      v_mood_bias := 0.012;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    ELSIF v_roll < 0.40 THEN
      -- Low Tide: weak bear
      v_mood := 'low_tide';
      v_mood_bias := -0.012;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    ELSIF v_roll < 0.60 THEN
      -- Storm: high volatility, bidirectional
      v_mood := 'storm';
      v_mood_bias := CASE WHEN random() < 0.5 THEN 0.01 ELSE -0.01 END;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    ELSE
      -- Calm: stable
      v_mood := 'calm';
      v_mood_bias := 0;
      v_mood_expires_at := now() + (2 + floor(random() * 4)) * interval '1 hour';
    END IF;

    UPDATE market_state SET
      mood = v_mood,
      mood_bias = v_mood_bias,
      mood_expires_at = v_mood_expires_at,
      next_update_at = now() + interval '1 hour'
    WHERE id = 1;
  ELSE
    UPDATE market_state SET
      next_update_at = now() + interval '1 hour'
    WHERE id = 1;
  END IF;

  FOR r IN
    SELECT fm.fish_id, fm.multiplier, fm.history, fs.bite_rarity
      FROM fish_market fm
      JOIN fish_species fs ON fs.id = fm.fish_id
  LOOP
    CASE r.bite_rarity
      WHEN 1 THEN v_volatility := 0.04;
      WHEN 2 THEN v_volatility := 0.06;
      WHEN 3 THEN v_volatility := 0.09;
      WHEN 4 THEN v_volatility := 0.14;
      ELSE        v_volatility := 0.20;
    END CASE;

    IF v_mood = 'storm' THEN
      v_volatility := v_volatility * 1.5;
    ELSIF v_mood = 'kraken' THEN
      v_volatility := v_volatility * 2.0;
    ELSIF v_mood IN ('bounty_season', 'cursed_waters') THEN
      v_volatility := v_volatility * 1.2;
    END IF;

    v_drift := 0.08 * (1.0 - r.multiplier::float);
    v_noise := (random() + random() + random() - 1.5) * v_volatility;

    v_new_mult := GREATEST(0.40, LEAST(2.50,
      r.multiplier::float + v_drift + v_noise + v_mood_bias::float
    ));

    v_history := r.history;
    v_history := v_history || to_jsonb(round(r.multiplier::numeric, 2));
    IF jsonb_array_length(v_history) > 24 THEN
      v_history := (SELECT jsonb_agg(elem ORDER BY ord) FROM (
        SELECT elem, ord FROM jsonb_array_elements(v_history) WITH ORDINALITY AS t(elem, ord)
        ORDER BY ord DESC LIMIT 24
      ) sub);
    END IF;

    UPDATE fish_market SET
      prev_multiplier = multiplier,
      multiplier = round(v_new_mult::numeric, 2),
      history = v_history,
      updated_at = now()
    WHERE fish_id = r.fish_id;
  END LOOP;
END;
$function$
;
revoke all on function public.update_fish_market() from public, anon, authenticated;
grant execute on function public.update_fish_market() to anon;
grant execute on function public.update_fish_market() to authenticated;
grant execute on function public.update_fish_market() to public;
grant execute on function public.update_fish_market() to service_role;

CREATE OR REPLACE FUNCTION public.upsert_bait(p_user_id uuid, p_bait_type text, p_qty integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO bait_inventory (user_id, bait_type, quantity)
  VALUES (p_user_id, p_bait_type, p_qty)
  ON CONFLICT (user_id, bait_type)
  DO UPDATE SET quantity = bait_inventory.quantity + EXCLUDED.quantity;
END;
$function$
;
revoke all on function public.upsert_bait(p_user_id uuid, p_bait_type text, p_qty integer) from public, anon, authenticated;
grant execute on function public.upsert_bait(p_user_id uuid, p_bait_type text, p_qty integer) to service_role;

CREATE OR REPLACE FUNCTION public.vigil_total(v jsonb)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $function$
  select coalesce(sum(greatest(0, least(5, (value->>'rank')::int))), 0)::int
  from jsonb_each(coalesce(v, '{}'::jsonb))
$function$
;
revoke all on function public.vigil_total(v jsonb) from public, anon, authenticated;
grant execute on function public.vigil_total(v jsonb) to anon;
grant execute on function public.vigil_total(v jsonb) to authenticated;
grant execute on function public.vigil_total(v jsonb) to public;
grant execute on function public.vigil_total(v jsonb) to service_role;

CREATE OR REPLACE FUNCTION public.wallet_add(uid uuid, col text, delta bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v bigint;
begin
  if col not in ('doubloons','gems','blood_gems','gauntlet_fathoms','casino_chips') then
    raise exception 'wallet_add: column % not allowed', col;
  end if;
  execute format(
    'update public.profiles set %1$I = %1$I + $2 where id = $1 and %1$I + $2 >= 0 returning %1$I', col)
    into v using uid, delta;
  return v;  -- null = not enough (or no such player): nothing changed
end $function$
;
revoke all on function public.wallet_add(uid uuid, col text, delta bigint) from public, anon, authenticated;
grant execute on function public.wallet_add(uid uuid, col text, delta bigint) to service_role;
