-- Views and materialized views
-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;
-- change the database, then re-run the script.

create or replace view public.leaderboard_achievements as
 SELECT p.id AS user_id,
    p.username,
    count(ua.achievement_key)::integer AS score
   FROM profiles p
     LEFT JOIN user_achievements ua ON ua.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin
  GROUP BY p.id, p.username;

create materialized view if not exists public.leaderboard_blackjack as
 WITH running AS (
         SELECT blackjack_hands.user_id,
            blackjack_hands.settled_at,
            sum(blackjack_hands.net_delta) OVER (PARTITION BY blackjack_hands.user_id ORDER BY blackjack_hands.settled_at, blackjack_hands.id) AS cum
           FROM blackjack_hands
          WHERE blackjack_hands.status = 'settled'::text AND blackjack_hands.net_delta IS NOT NULL AND blackjack_hands.settled_at IS NOT NULL
        ), totals AS (
         SELECT blackjack_hands.user_id,
            sum(blackjack_hands.net_delta)::integer AS score
           FROM blackjack_hands
          WHERE blackjack_hands.status = 'settled'::text AND blackjack_hands.net_delta IS NOT NULL AND blackjack_hands.settled_at IS NOT NULL
          GROUP BY blackjack_hands.user_id
        ), reached AS (
         SELECT t.user_id,
            t.score,
            ( SELECT min(r.settled_at) AS min
                   FROM running r
                  WHERE r.user_id = t.user_id AND r.cum >= t.score) AS created_at
           FROM totals t
        )
 SELECT p.id AS user_id,
    p.username,
    reached.score,
    reached.created_at
   FROM profiles p
     JOIN reached ON reached.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin;

create or replace view public.leaderboard_bounty_points as
 SELECT id AS user_id,
    username,
    COALESCE(bounty_points, 0) AS score,
    created_at
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create or replace view public.leaderboard_collection as
 SELECT p.id AS user_id,
    p.username,
    count(DISTINCT uc.card_variant_id)::integer AS score
   FROM profiles p
     LEFT JOIN user_collection uc ON uc.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin
  GROUP BY p.id, p.username;

create materialized view if not exists public.leaderboard_den as
 WITH events AS (
         SELECT blackjack_hands.user_id,
            blackjack_hands.settled_at AS ts,
            blackjack_hands.net_delta AS delta
           FROM blackjack_hands
          WHERE blackjack_hands.status = 'settled'::text AND blackjack_hands.net_delta IS NOT NULL AND blackjack_hands.settled_at IS NOT NULL
        UNION ALL
         SELECT slot_spins.user_id,
            slot_spins.created_at AS ts,
            slot_spins.payout - slot_spins.wager AS delta
           FROM slot_spins
        UNION ALL
         SELECT roulette_spins.user_id,
            roulette_spins.created_at AS ts,
            roulette_spins.net_chips AS delta
           FROM roulette_spins
        ), running AS (
         SELECT events.user_id,
            events.ts,
            sum(events.delta) OVER (PARTITION BY events.user_id ORDER BY events.ts) AS cum
           FROM events
        ), totals AS (
         SELECT events.user_id,
            sum(events.delta)::integer AS score
           FROM events
          GROUP BY events.user_id
        ), reached AS (
         SELECT t.user_id,
            t.score,
            ( SELECT min(r.ts) AS min
                   FROM running r
                  WHERE r.user_id = t.user_id AND r.cum >= t.score) AS created_at
           FROM totals t
        )
 SELECT p.id AS user_id,
    p.username,
    reached.score,
    reached.created_at
   FROM profiles p
     JOIN reached ON reached.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin;

create or replace view public.leaderboard_dons_gauntlet as
 SELECT id AS user_id,
    username,
    dons_gauntlet_best_depth AS score,
    dons_gauntlet_best_depth_ms AS time_ms,
    dons_gauntlet_best_depth_at AS created_at
   FROM profiles p
  WHERE dons_gauntlet_best_depth > 0 AND is_admin = false AND username IS NOT NULL;

create or replace view public.leaderboard_dons_gauntlet_hardcore as
 SELECT id AS user_id,
    username,
    dons_gauntlet_hc_best_depth AS score,
    dons_gauntlet_hc_best_depth_ms AS time_ms,
    dons_gauntlet_hc_best_depth_at AS created_at
   FROM profiles p
  WHERE dons_gauntlet_hc_best_depth > 0 AND is_admin = false AND username IS NOT NULL;

create or replace view public.leaderboard_exchange as
 SELECT b.user_id,
    p.username,
    sum(COALESCE(b.payout, 0)) - sum(b.stake) AS score,
    max(b.settled_at) AS created_at
   FROM exchange_bets b
     JOIN profiles p ON p.id = b.user_id
  WHERE b.status <> 'open'::text AND COALESCE(p.is_admin, false) = false
  GROUP BY b.user_id, p.username
 HAVING count(*) > 0;

create or replace view public.leaderboard_exchange_week as
 SELECT b.user_id,
    p.username,
    sum(COALESCE(b.payout, 0)) - sum(b.stake) AS score,
    max(b.settled_at) AS created_at
   FROM exchange_bets b
     JOIN profiles p ON p.id = b.user_id
  WHERE b.status <> 'open'::text AND b.settled_at >= date_trunc('week'::text, now()) AND COALESCE(p.is_admin, false) = false
  GROUP BY b.user_id, p.username
 HAVING count(*) > 0;

create or replace view public.leaderboard_expedition as
 SELECT id AS user_id,
    username,
    COALESCE(expedition_xp, 0) AS score,
    created_at
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create materialized view if not exists public.leaderboard_fish_slots as
 WITH running AS (
         SELECT slot_spins.user_id,
            slot_spins.created_at AS ts,
            sum(slot_spins.payout - slot_spins.wager) OVER (PARTITION BY slot_spins.user_id ORDER BY slot_spins.created_at, slot_spins.id) AS cum
           FROM slot_spins
        ), totals AS (
         SELECT slot_spins.user_id,
            sum(slot_spins.payout - slot_spins.wager)::integer AS score
           FROM slot_spins
          GROUP BY slot_spins.user_id
        ), reached AS (
         SELECT t.user_id,
            t.score,
            ( SELECT min(r.ts) AS min
                   FROM running r
                  WHERE r.user_id = t.user_id AND r.cum >= t.score) AS created_at
           FROM totals t
        )
 SELECT p.id AS user_id,
    p.username,
    reached.score,
    reached.created_at
   FROM profiles p
     JOIN reached ON reached.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin;

create or replace view public.leaderboard_fish_sold as
 SELECT id AS user_id,
    username,
    COALESCE(fish_sold_doubloons, 0::bigint) AS score,
    created_at
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create or replace view public.leaderboard_fishing as
 SELECT id AS user_id,
    username,
    COALESCE(fishing_xp, 0::bigint) AS score,
    created_at
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create or replace view public.leaderboard_gauntlet as
 SELECT id AS user_id,
    username,
    gauntlet_best_depth AS score,
    gauntlet_best_depth_ms AS time_ms,
    gauntlet_best_depth_at AS created_at
   FROM profiles p
  WHERE gauntlet_best_depth > 0 AND is_admin = false AND username IS NOT NULL;

create or replace view public.leaderboard_gauntlet_hardcore as
 SELECT id AS user_id,
    username,
    gauntlet_hc_best_depth AS score,
    gauntlet_hc_best_depth_ms AS time_ms,
    gauntlet_hc_best_depth_at AS created_at
   FROM profiles p
  WHERE gauntlet_hc_best_depth > 0 AND is_admin = false AND username IS NOT NULL;

create or replace view public.leaderboard_gauntlet_hit as
 SELECT id AS user_id,
    username,
    gauntlet_big_hit AS score,
    gauntlet_big_hit_at AS created_at
   FROM profiles
  WHERE gauntlet_big_hit > 0 AND is_admin = false AND username IS NOT NULL;

create or replace view public.leaderboard_packs as
 SELECT p.id AS user_id,
    p.username,
    count(ph.id)::integer AS score
   FROM profiles p
     LEFT JOIN pack_history ph ON ph.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin
  GROUP BY p.id, p.username;

create or replace view public.leaderboard_perfect_streak as
 SELECT id AS user_id,
    username,
    COALESCE(highest_perfect_streak, 0) AS score,
    NULL::text AS zone,
    COALESCE(highest_streak_set_at, created_at) AS created_at,
    0 AS zone_rank
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create materialized view if not exists public.leaderboard_roulette as
 WITH running AS (
         SELECT roulette_spins.user_id,
            roulette_spins.created_at AS ts,
            sum(roulette_spins.net_chips) OVER (PARTITION BY roulette_spins.user_id ORDER BY roulette_spins.created_at, roulette_spins.id) AS cum
           FROM roulette_spins
        ), totals AS (
         SELECT roulette_spins.user_id,
            sum(roulette_spins.net_chips)::integer AS score
           FROM roulette_spins
          GROUP BY roulette_spins.user_id
        ), reached AS (
         SELECT t.user_id,
            t.score,
            ( SELECT min(r.ts) AS min
                   FROM running r
                  WHERE r.user_id = t.user_id AND r.cum >= t.score) AS created_at
           FROM totals t
        )
 SELECT p.id AS user_id,
    p.username,
    reached.score,
    reached.created_at
   FROM profiles p
     JOIN reached ON reached.user_id = p.id
  WHERE p.username IS NOT NULL AND NOT p.is_admin;

create or replace view public.leaderboard_species as
 SELECT id AS user_id,
    username,
    COALESCE(lifetime_species_count, 0) AS score,
    created_at
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create or replace view public.leaderboard_streak as
 SELECT id AS user_id,
    username,
    COALESCE(fotd_streak, 0) AS score
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create or replace view public.leaderboard_trophies as
 SELECT id AS user_id,
    username,
    COALESCE(trophy_size_catches, 0) AS score,
    created_at
   FROM profiles
  WHERE username IS NOT NULL AND NOT is_admin;

create or replace view public.leaderboard_vigil as
 SELECT id AS user_id,
    username,
    vigil_total(ancient_vigil) AS score,
    created_at
   FROM profiles
  WHERE vigil_total(ancient_vigil) > 6 AND is_admin = false AND username IS NOT NULL;
