-- Triggers (public tables and auth.users)
-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;
-- change the database, then re-run the script.

CREATE TRIGGER trg_default_username BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_default_username();
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
