-- pg_cron jobs
-- Generated by scripts/snapshot-schema.mts from the live database. Do not edit by hand;
-- change the database, then re-run the script.

select cron.schedule('exchange-bets-settle', '2 * * * *', 'SELECT settle_exchange_bets()');
select cron.schedule('exchange-indexes-tick', '0 * * * *', 'SELECT update_exchange_indexes()');
select cron.schedule('fish-market-tick', '0 * * * *', 'SELECT update_fish_market()');
select cron.schedule('reconcile-premium-daily', '0 4 * * *', '
  SELECT net.http_post(
    url     := ''https://pwvndjczpdcttmyvnsyq.supabase.co/functions/v1/reconcile-premium'',
    headers := ''{"Content-Type": "application/json", "Authorization": "Bearer <REDACTED: set from the live job or Vault>"}''::jsonb,
    body    := ''{}''::jsonb
  );
  ');
select cron.schedule('refresh-casino-leaderboards', '*/5 * * * *', 'SELECT public.refresh_casino_leaderboards()');
