// THE PARLOR'S QUESTION BANK FOR THE PORT (Kong, 2026-10-03: "long lasting").
//
// One bank, three sources, every question with a stable id (a hash of its
// words, so a captain's "seen" list survives a rebuild):
//   1. web/content/trivia.json: the web's weeks already written (boards and
//      ladders flattened; capstan phrases kept as phrases).
//   2. content/trivia_fresh.json: the fresh set written for the port and
//      fact-checked question by question (the trivia-bank-800 workflow).
//   3. Our own game: every fish's Log fact with its name veiled (the same veil
//      the treasure hunts use), which water it is fished from, and how rare it
//      is. These are "game" questions; the treasure hunts ask them too, so the
//      Parlor teaches what the hunts want.
//
//   node tools/build-trivia.mjs        (from godot/game)
//
// Writes content/trivia_bank.json: { questions: [...], phrases: [...] }.
// The bank carries the answers; it ships only in the game.

import fs from 'fs'
import path from 'path'
import crypto from 'crypto'
import { fileURLToPath } from 'url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const GAME = path.join(HERE, '..')
const WEB = path.join(GAME, '..', '..', 'web')

const id = (s) => crypto.createHash('sha1').update(s.trim().toLowerCase()).digest('hex').slice(0, 12)
const norm = (s) => s.trim().toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ')

// A fixed shuffle (so a rebuild gives the same options in the same places).
function seeded(seed) { let s = seed >>> 0; return () => { s = (Math.imul(s, 1664525) + 1013904223) >>> 0; return s / 4294967296 } }
function hashInt(str) { return parseInt(crypto.createHash('sha1').update(str).digest('hex').slice(0, 8), 16) }

// NO EM-DASHES in the copy the port shows (the house rule). The web's
// questions carry some, so they are reworded here as the bank is built, by
// question id: the id and the duplicate check stay on the web's own words, so
// a captain's "seen" list survives. Anything not listed falls back to commas.
const UNDASHED = {
  'ff40df3c1ad0': { explanation: "Gills contain thin membranes where dissolved oxygen passes into the fish's blood while carbon dioxide exits, the same gas exchange that happens in our lungs." },
  'b69de837dc6a': { explanation: 'All three terms (chum, burley and groundbait) refer to scattered fish scraps used to attract and concentrate fish in a fishing area.' },
  '2126c048938b': { explanation: 'Countershading (a dark back and a light belly) makes fish harder to spot from above (blending with darkness) or below (blending with light from the surface).' },
  'dcdc3428f708': { explanation: 'Sharks have a heterocercal tail where the upper lobe is longer, housing the spine. This generates lift as well as thrust.' },
  'a919237e6fd1': { explanation: 'Sirens were mythical creatures whose irresistible song drove sailors to wreck their ships on rocky coasts. Odysseus famously had himself tied to the mast to resist them.' },
  '73e78a36dbb7': { options: { 0: 'Bone (only cartilage)' } },
  'ce4810f06540': { explanation: "These gel-filled pores around a shark's snout sense the faint bioelectric fields generated by all living animals' muscle contractions, useful even in murky water." },
  '0eb3864ccf1d': { explanation: 'Diel vertical migration is one of the largest daily animal movements on Earth: billions of creatures rise to feed at night, then descend to avoid daytime predators.' },
  '1b205c15bd91': { explanation: 'The Vasa capsized and sank roughly 1,300 meters into her maiden voyage in Stockholm harbor. Top-heavy by design, she was felled by a modest gust of wind.' },
  'd711f35e32cb': { explanation: "A purse seine encircles a school of fish, then a line along the bottom is pulled tight, 'pursing' the net closed so fish cannot dive to escape. It's widely used for tuna and sardines." },
  '4fce20c68666': { explanation: 'Pacific salmon (including sockeye, chinook and coho) undergo semelparous reproduction: they spawn once and then die, their decaying bodies fertilizing the very streams where their eggs rest.' },
  'c83d71dd5c2b': { explanation: "HMS Swallow, captained by Chaloner Ogle, surprised Roberts' fleet off Cape Lopez. Roberts was killed by grapeshot, and Ogle became one of the most successful pirate hunters in Royal Navy history." },
  '46aaeb798a7c': { explanation: 'Many grouper species are protogynous hermaphrodites: they begin life as females and transition to male when they reach a certain size or social role.' },
  '8b93b4d071b7': { explanation: 'Oilfish store wax esters rather than triglyceride fats for buoyancy control. These esters are indigestible to humans, causing infamous gastrointestinal effects.' },
  '538f3fe5ee3b': { explanation: 'Below about 1,000 meters, no sunlight penetrates. This is called the midnight zone, or aphotic zone, where bioluminescence is the only light source.' },
  'bca6e35e0d3c': { explanation: 'Bacteria at hydrothermal vents use chemosynthesis, converting hydrogen sulfide into energy and forming the base of entire food webs with no sunlight required.' },
  '761650d25682': { explanation: 'The Kraken originates in Scandinavian maritime legend: a colossal sea monster capable of dragging ships to the depths, likely inspired by real giant squid sightings.' },
  'bb6b0f193270': { explanation: "The 1530 agreement required the Knights to pay one Maltese falcon per year to the Viceroy of Sicily, the inspiration for Dashiell Hammett's famous novel." },
  '3f42f5c8fbfb': { explanation: 'Ukai has been practiced in Japan for over 1,300 years. Cormorants wear a snare near their throat so they cannot swallow large fish, delivering the catch to the fisherman.' },
  'cf79fb11ee15': { explanation: "Tetrodotoxin is concentrated in a pufferfish's liver, skin and ovaries. It blocks nerve signals and has no antidote, yet prepared as fugu, it's a prized delicacy in Japan." },
  '7634b4f88eb8': { explanation: 'A trawler brought the first modern specimen to a South African museum near the Chalumna River. It stunned scientists: the coelacanth lineage dates back over 400 million years.' },
  '35c5b8ebc349': { explanation: 'The Mayflower crossed the Atlantic in roughly 66 days. It was a modest merchant vessel never designed for colonists, and about 102 passengers endured the journey in cramped holds.' },
  '503967e468af': { explanation: 'Lead weights come in many shapes (egg, bullet, split shot) and sink the bait to the target depth. Growing environmental concerns have spurred a shift toward tungsten and tin alternatives.' },
  '9b4a47a99ee3': { explanation: 'A snailfish of the family Liparidae, sometimes called the hadal snailfish, was filmed by a Japanese research team in the Izu-Ogasawara Trench, breaking the previous depth record for fish.' },
  'e173d6072133': { explanation: 'Atlantis was described by the ancient Greek philosopher Plato around 360 BCE as a powerful civilization that sank into the sea. It remains one of the most enduring myths in Western culture.' },
  '15320673d6f4': { explanation: 'Salmon are anadromous fish that hatch in freshwater, migrate to the ocean to mature, then navigate back to their exact birth stream to spawn, often leaping waterfalls along the way.' },
  '76e46a8bf5f2': { explanation: 'Bioluminescence is light produced by living organisms through chemical reactions, used by deep-sea creatures to lure prey, communicate, or confuse predators in the pitch-dark abyss.' },
  '4873dbaf66f6': { explanation: 'The SOFAR (Sound Fixing and Ranging) channel is a depth of minimum sound speed where sound waves become trapped and travel thousands of miles. Blue whales exploit it to communicate across ocean basins.' },
  'fd7d55e20b59': { explanation: 'In Greek mythology, Sirens were creatures whose enchanting song compelled sailors to steer toward rocks and shipwreck. Odysseus famously had himself tied to the mast to hear them safely.' },
  '716625a0570e': { explanation: "Ching Shih commanded the Red Flag Fleet (at its peak over 1,800 vessels and 80,000 sailors), becoming one of history's most powerful and feared pirates before negotiating a remarkable amnesty." },
  '7398990bb2ac': { explanation: "The fishhook is one of humanity's oldest tools. Archaeological examples date back over 23,000 years, and the basic barbed design has changed remarkably little since ancient times." },
  '0967fc039a89': { explanation: "Purse seining works by encircling a fish school with a net, then drawing a line through rings at the bottom to 'close the purse' and trap the fish. It's the primary method used to catch tuna and sardines." },
  '78414300a0af': { explanation: "The bow is the forward-most part of a ship's hull, designed to cut through water efficiently, opposite the stern at the rear." },
  '656fe8e09f79': { explanation: "Bartholomew Roberts's ship articles were among the most detailed on record, covering voting rights, injury pay and behavior: a kind of pirate constitution." },
  'c915cd78a95b': { explanation: 'Sharks belong to class Chondrichthyes: their skeletons are made entirely of cartilage, which is lighter and more flexible than bone.' },
  '72a8290d6f1f': { explanation: 'Catadromous fish like eels live in fresh water but travel to the ocean to reproduce, the reverse of anadromous salmon.' },
  'e1e586546316': { explanation: "Henry Every's capture of the Ganj-i-Sawai, one of the richest prizes in piracy history, outraged the Mughal emperor and forced the East India Company to pay reparations to avoid losing their trading rights in India." },
  'f5bff58f4a58': { explanation: 'Walking the plank (being forced off a board extended over the sea) is a classic pirate punishment, though it appears more in legend and literature than verified historical record.' },
  '596b756e16ab': { explanation: 'Catadromous fish like European eels do the reverse of salmon: they grow up in rivers but return to the ocean to spawn and die.' },
  '36d91aeb2fce': { explanation: "Roberts's Articles were unusually detailed, covering shares of plunder, lights-out hours, gambling rules and compensation for injuries, a rare surviving example of a pirate ship's written code." },
  '72c345ba6b16': { explanation: 'Letters of Marque and Reprisal were legal documents issued by a sovereign that authorized private ship captains to attack and seize enemy vessels, distinguishing privateers from outright pirates in law.' },
  'a32dc3f18642': { explanation: 'Female anglerfish dangle a modified dorsal spine tipped with light-producing bacteria, a bioluminescent lure that draws curious prey within striking distance.' },
  'ac823c7c7ddd': { question: "Which pirate flag, solid black with a white skeleton, belonged to Edward 'Blackbeard' Low's rival, Emanuel Wynn?" },
  '32d2c3339820': { explanation: 'Marshallese and other Micronesian navigators used wave-piloting (lying in canoes to feel how islands deflect and reflect ocean swells) to navigate thousands of miles without instruments.' },
}
// The fallback for a dash no one has reworded yet: a comma.
const undash = (t) => String(t).replace(/\s*—\s*/g, ', ')

const questions = []
const seen = new Set()
function add(q, source) {
  const key = norm(q.question)
  if (seen.has(key)) return
  if (!Array.isArray(q.options) || q.options.length !== 4) return
  if (new Set(q.options.map(o => o.trim().toLowerCase())).size !== 4) return
  seen.add(key)
  const qid = id(q.question)
  const fix = UNDASHED[qid] ?? {}
  const options = q.options.map((o, i) => undash(fix.options?.[i] ?? o))
  questions.push({ id: qid, source, category: q.category, tier: q.tier, question: undash(fix.question ?? q.question), options, correct_index: q.correct_index, explanation: undash(fix.explanation ?? q.explanation ?? '') })
}

// 1. The web's.
const web = JSON.parse(fs.readFileSync(path.join(WEB, 'content', 'trivia.json'), 'utf8'))
for (const week of web.boards) for (const q of week) add(q, 'web')
for (const lad of web.ladders) for (const q of lad) add({ ...q, category: q.category ?? 'LORE', tier: q.tier ?? 2 }, 'web')
const phrases = []
const seenP = new Set()
for (const set of web.capstan) for (const p of set) if (!seenP.has(p.phrase)) { seenP.add(p.phrase); phrases.push({ id: id(p.phrase), phrase: p.phrase, category: p.category }) }

// 2. The fresh set.
const freshPath = path.join(GAME, 'content', 'trivia_fresh.json')
if (fs.existsSync(freshPath)) {
  const fresh = JSON.parse(fs.readFileSync(freshPath, 'utf8'))
  for (const q of fresh.questions ?? []) add(q, 'fresh')
  for (const p of fresh.phrases ?? []) {
    const ph = String(p.phrase).toUpperCase().replace(/[^A-Z ]/g, '').replace(/\s+/g, ' ').trim()
    if (ph && !seenP.has(ph)) { seenP.add(ph); phrases.push({ id: id(ph), phrase: ph, category: p.category }) }
  }
}

// 3. Our own game.
const species = JSON.parse(fs.readFileSync(path.join(GAME, 'content', 'fish_species.json'), 'utf8'))
const WATERS = { shallows: 'The Shallows', open_waters: 'Open Waters', deep: 'The Deep', abyss: 'The Abyss', ancient_deep: 'The Ancient Deep' }
const RARITY = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary']
const tierOf = (r) => (r <= 2 ? 1 : r === 3 ? 2 : 3)

// The veil: the fish's name out of its own fact (core/clues.gd veil()).
function veil(text, name) {
  const words = name.split(' ')
  const names = [name]
  if (words.length > 1 && words[words.length - 1].length > 3) names.push(words[words.length - 1])
  let out = text
  for (const n of names) {
    const e = n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    out = out.replace(new RegExp(`\\b(the |a |an )?${e}(e?s)?\\b(?= (are|were|have|can|live|lie|grow|feed|hunt|spend))`, 'gi'), 'they')
    out = out.replace(new RegExp(`\\b(the |a |an )?${e}(e?s)?\\b`, 'gi'), 'this fish')
  }
  return out.split('. ').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('. ')
}

function placeCorrect(correct, wrong, seedStr) {
  const r = seeded(hashInt(seedStr))
  const at = Math.floor(r() * 4)
  const opts = [...wrong.slice(0, 3)]
  opts.splice(at, 0, correct)
  return { options: opts, correct_index: at }
}

let made = 0
for (const f of species) {
  const fact = (f.fun_fact || f.description || '').trim()
  const rarity = Number(f.bite_rarity ?? 1)
  const water = WATERS[f.habitat]
  if (!water) continue
  // Which fish is this? (Three others from the same water, chosen per fish.)
  if (fact && fact.length > 30) {
    const said = veil(fact, f.name)
    if (!said.toLowerCase().includes(f.name.toLowerCase())) {
      const others = species.filter(o => o.habitat === f.habitat && o.id !== f.id)
        .sort((a, b) => hashInt(f.name + a.name) - hashInt(f.name + b.name))
        .map(o => o.name)
      if (others.length >= 3) {
        const { options, correct_index } = placeCorrect(f.name, others, 'who' + f.name)
        add({ category: 'FISH', tier: tierOf(rarity), question: `Which fish does your Log describe so: "${said}"`, options, correct_index, explanation: `That is the ${f.name}, from ${water}.` }, 'game')
        made++
      }
    }
  }
  // Where is it fished?
  const wrongW = Object.values(WATERS).filter(w => w !== water).sort((a, b) => hashInt(f.name + a) - hashInt(f.name + b))
  {
    const { options, correct_index } = placeCorrect(water, wrongW, 'where' + f.name)
    add({ category: 'CATCH', tier: tierOf(rarity), question: `Where do captains land the ${f.name}?`, options, correct_index, explanation: `The ${f.name} bites in ${water}.` }, 'game')
    made++
  }
  // How rare?
  {
    const right = RARITY[Math.max(0, Math.min(4, rarity - 1))]
    const wrongR = RARITY.filter(x => x !== right).sort((a, b) => hashInt(f.name + 'r' + a) - hashInt(f.name + 'r' + b))
    const { options, correct_index } = placeCorrect(right, wrongR, 'rare' + f.name)
    add({ category: 'CATCH', tier: Math.min(3, tierOf(rarity) + 1), question: `How rare a catch is the ${f.name}?`, options, correct_index, explanation: `The ${f.name} is ${right.toLowerCase()}.` }, 'game')
    made++
  }
}

const by = (s) => questions.filter(q => q.source === s).length
fs.writeFileSync(path.join(GAME, 'content', 'trivia_bank.json'), JSON.stringify({ built: new Date().toISOString().slice(0, 10), questions, phrases }, null, 0))
console.log(`  trivia bank: ${questions.length} questions (web ${by('web')}, fresh ${by('fresh')}, game ${by('game')}), ${phrases.length} capstan phrases`)
